// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api.proto

package supervisorv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/noosxe/runnero/internal/pb/supervisor/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "supervisor.v1.AuthService"
	// PoolServiceName is the fully-qualified name of the PoolService service.
	PoolServiceName = "supervisor.v1.PoolService"
	// AuthProfileServiceName is the fully-qualified name of the AuthProfileService service.
	AuthProfileServiceName = "supervisor.v1.AuthProfileService"
	// OnboardingServiceName is the fully-qualified name of the OnboardingService service.
	OnboardingServiceName = "supervisor.v1.OnboardingService"
	// AnalyticsServiceName is the fully-qualified name of the AnalyticsService service.
	AnalyticsServiceName = "supervisor.v1.AnalyticsService"
	// LogServiceName is the fully-qualified name of the LogService service.
	LogServiceName = "supervisor.v1.LogService"
	// RenovateServiceName is the fully-qualified name of the RenovateService service.
	RenovateServiceName = "supervisor.v1.RenovateService"
	// ImageUpdateServiceName is the fully-qualified name of the ImageUpdateService service.
	ImageUpdateServiceName = "supervisor.v1.ImageUpdateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceSetupAdminProcedure is the fully-qualified name of the AuthService's SetupAdmin RPC.
	AuthServiceSetupAdminProcedure = "/supervisor.v1.AuthService/SetupAdmin"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/supervisor.v1.AuthService/Login"
	// AuthServiceGetSessionProcedure is the fully-qualified name of the AuthService's GetSession RPC.
	AuthServiceGetSessionProcedure = "/supervisor.v1.AuthService/GetSession"
	// PoolServiceListPoolsProcedure is the fully-qualified name of the PoolService's ListPools RPC.
	PoolServiceListPoolsProcedure = "/supervisor.v1.PoolService/ListPools"
	// PoolServiceCreatePoolProcedure is the fully-qualified name of the PoolService's CreatePool RPC.
	PoolServiceCreatePoolProcedure = "/supervisor.v1.PoolService/CreatePool"
	// PoolServiceUpdatePoolProcedure is the fully-qualified name of the PoolService's UpdatePool RPC.
	PoolServiceUpdatePoolProcedure = "/supervisor.v1.PoolService/UpdatePool"
	// PoolServiceDeletePoolProcedure is the fully-qualified name of the PoolService's DeletePool RPC.
	PoolServiceDeletePoolProcedure = "/supervisor.v1.PoolService/DeletePool"
	// PoolServiceWatchPoolsProcedure is the fully-qualified name of the PoolService's WatchPools RPC.
	PoolServiceWatchPoolsProcedure = "/supervisor.v1.PoolService/WatchPools"
	// PoolServiceListRunnersProcedure is the fully-qualified name of the PoolService's ListRunners RPC.
	PoolServiceListRunnersProcedure = "/supervisor.v1.PoolService/ListRunners"
	// PoolServiceTerminateRunnerProcedure is the fully-qualified name of the PoolService's
	// TerminateRunner RPC.
	PoolServiceTerminateRunnerProcedure = "/supervisor.v1.PoolService/TerminateRunner"
	// PoolServiceWatchRunnersProcedure is the fully-qualified name of the PoolService's WatchRunners
	// RPC.
	PoolServiceWatchRunnersProcedure = "/supervisor.v1.PoolService/WatchRunners"
	// PoolServiceDiscoverTargetsProcedure is the fully-qualified name of the PoolService's
	// DiscoverTargets RPC.
	PoolServiceDiscoverTargetsProcedure = "/supervisor.v1.PoolService/DiscoverTargets"
	// AuthProfileServiceListAuthProfilesProcedure is the fully-qualified name of the
	// AuthProfileService's ListAuthProfiles RPC.
	AuthProfileServiceListAuthProfilesProcedure = "/supervisor.v1.AuthProfileService/ListAuthProfiles"
	// AuthProfileServiceCreateAuthProfileProcedure is the fully-qualified name of the
	// AuthProfileService's CreateAuthProfile RPC.
	AuthProfileServiceCreateAuthProfileProcedure = "/supervisor.v1.AuthProfileService/CreateAuthProfile"
	// AuthProfileServiceDeleteAuthProfileProcedure is the fully-qualified name of the
	// AuthProfileService's DeleteAuthProfile RPC.
	AuthProfileServiceDeleteAuthProfileProcedure = "/supervisor.v1.AuthProfileService/DeleteAuthProfile"
	// OnboardingServiceGetOnboardingStatusProcedure is the fully-qualified name of the
	// OnboardingService's GetOnboardingStatus RPC.
	OnboardingServiceGetOnboardingStatusProcedure = "/supervisor.v1.OnboardingService/GetOnboardingStatus"
	// OnboardingServiceGetAppSettingsProcedure is the fully-qualified name of the OnboardingService's
	// GetAppSettings RPC.
	OnboardingServiceGetAppSettingsProcedure = "/supervisor.v1.OnboardingService/GetAppSettings"
	// OnboardingServiceSetAppSettingProcedure is the fully-qualified name of the OnboardingService's
	// SetAppSetting RPC.
	OnboardingServiceSetAppSettingProcedure = "/supervisor.v1.OnboardingService/SetAppSetting"
	// OnboardingServiceCompleteOnboardingProcedure is the fully-qualified name of the
	// OnboardingService's CompleteOnboarding RPC.
	OnboardingServiceCompleteOnboardingProcedure = "/supervisor.v1.OnboardingService/CompleteOnboarding"
	// AnalyticsServiceGetJobHistoryProcedure is the fully-qualified name of the AnalyticsService's
	// GetJobHistory RPC.
	AnalyticsServiceGetJobHistoryProcedure = "/supervisor.v1.AnalyticsService/GetJobHistory"
	// AnalyticsServiceGetJobRecordProcedure is the fully-qualified name of the AnalyticsService's
	// GetJobRecord RPC.
	AnalyticsServiceGetJobRecordProcedure = "/supervisor.v1.AnalyticsService/GetJobRecord"
	// AnalyticsServiceGetSystemStatsProcedure is the fully-qualified name of the AnalyticsService's
	// GetSystemStats RPC.
	AnalyticsServiceGetSystemStatsProcedure = "/supervisor.v1.AnalyticsService/GetSystemStats"
	// AnalyticsServiceWatchDashboardProcedure is the fully-qualified name of the AnalyticsService's
	// WatchDashboard RPC.
	AnalyticsServiceWatchDashboardProcedure = "/supervisor.v1.AnalyticsService/WatchDashboard"
	// LogServiceStreamRunnerLogsProcedure is the fully-qualified name of the LogService's
	// StreamRunnerLogs RPC.
	LogServiceStreamRunnerLogsProcedure = "/supervisor.v1.LogService/StreamRunnerLogs"
	// LogServiceGetRunnerLogsProcedure is the fully-qualified name of the LogService's GetRunnerLogs
	// RPC.
	LogServiceGetRunnerLogsProcedure = "/supervisor.v1.LogService/GetRunnerLogs"
	// RenovateServiceTriggerRenovateRunProcedure is the fully-qualified name of the RenovateService's
	// TriggerRenovateRun RPC.
	RenovateServiceTriggerRenovateRunProcedure = "/supervisor.v1.RenovateService/TriggerRenovateRun"
	// RenovateServiceGetRenovateStatusProcedure is the fully-qualified name of the RenovateService's
	// GetRenovateStatus RPC.
	RenovateServiceGetRenovateStatusProcedure = "/supervisor.v1.RenovateService/GetRenovateStatus"
	// RenovateServiceListRenovateHistoryProcedure is the fully-qualified name of the RenovateService's
	// ListRenovateHistory RPC.
	RenovateServiceListRenovateHistoryProcedure = "/supervisor.v1.RenovateService/ListRenovateHistory"
	// ImageUpdateServiceCheckImageUpdateProcedure is the fully-qualified name of the
	// ImageUpdateService's CheckImageUpdate RPC.
	ImageUpdateServiceCheckImageUpdateProcedure = "/supervisor.v1.ImageUpdateService/CheckImageUpdate"
	// ImageUpdateServicePullImageProcedure is the fully-qualified name of the ImageUpdateService's
	// PullImage RPC.
	ImageUpdateServicePullImageProcedure = "/supervisor.v1.ImageUpdateService/PullImage"
	// ImageUpdateServiceListImageUpdatesProcedure is the fully-qualified name of the
	// ImageUpdateService's ListImageUpdates RPC.
	ImageUpdateServiceListImageUpdatesProcedure = "/supervisor.v1.ImageUpdateService/ListImageUpdates"
	// ImageUpdateServiceDismissImageUpdateProcedure is the fully-qualified name of the
	// ImageUpdateService's DismissImageUpdate RPC.
	ImageUpdateServiceDismissImageUpdateProcedure = "/supervisor.v1.ImageUpdateService/DismissImageUpdate"
)

// AuthServiceClient is a client for the supervisor.v1.AuthService service.
type AuthServiceClient interface {
	// Setup the initial local administrator account
	SetupAdmin(context.Context, *connect.Request[v1.SetupAdminRequest]) (*connect.Response[v1.SetupAdminResponse], error)
	// Login with local credentials to receive a session token
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Verify current session
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
}

// NewAuthServiceClient constructs a client for the supervisor.v1.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_api_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		setupAdmin: connect.NewClient[v1.SetupAdminRequest, v1.SetupAdminResponse](
			httpClient,
			baseURL+AuthServiceSetupAdminProcedure,
			connect.WithSchema(authServiceMethods.ByName("SetupAdmin")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+AuthServiceGetSessionProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	setupAdmin *connect.Client[v1.SetupAdminRequest, v1.SetupAdminResponse]
	login      *connect.Client[v1.LoginRequest, v1.LoginResponse]
	getSession *connect.Client[v1.GetSessionRequest, v1.GetSessionResponse]
}

// SetupAdmin calls supervisor.v1.AuthService.SetupAdmin.
func (c *authServiceClient) SetupAdmin(ctx context.Context, req *connect.Request[v1.SetupAdminRequest]) (*connect.Response[v1.SetupAdminResponse], error) {
	return c.setupAdmin.CallUnary(ctx, req)
}

// Login calls supervisor.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// GetSession calls supervisor.v1.AuthService.GetSession.
func (c *authServiceClient) GetSession(ctx context.Context, req *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the supervisor.v1.AuthService service.
type AuthServiceHandler interface {
	// Setup the initial local administrator account
	SetupAdmin(context.Context, *connect.Request[v1.SetupAdminRequest]) (*connect.Response[v1.SetupAdminResponse], error)
	// Login with local credentials to receive a session token
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Verify current session
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_api_proto.Services().ByName("AuthService").Methods()
	authServiceSetupAdminHandler := connect.NewUnaryHandler(
		AuthServiceSetupAdminProcedure,
		svc.SetupAdmin,
		connect.WithSchema(authServiceMethods.ByName("SetupAdmin")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetSessionHandler := connect.NewUnaryHandler(
		AuthServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(authServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/supervisor.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceSetupAdminProcedure:
			authServiceSetupAdminHandler.ServeHTTP(w, r)
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceGetSessionProcedure:
			authServiceGetSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) SetupAdmin(context.Context, *connect.Request[v1.SetupAdminRequest]) (*connect.Response[v1.SetupAdminResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AuthService.SetupAdmin is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AuthService.GetSession is not implemented"))
}

// PoolServiceClient is a client for the supervisor.v1.PoolService service.
type PoolServiceClient interface {
	ListPools(context.Context, *connect.Request[v1.ListPoolsRequest]) (*connect.Response[v1.ListPoolsResponse], error)
	CreatePool(context.Context, *connect.Request[v1.CreatePoolRequest]) (*connect.Response[v1.CreatePoolResponse], error)
	UpdatePool(context.Context, *connect.Request[v1.UpdatePoolRequest]) (*connect.Response[v1.UpdatePoolResponse], error)
	DeletePool(context.Context, *connect.Request[v1.DeletePoolRequest]) (*connect.Response[v1.DeletePoolResponse], error)
	// WatchPools provides near-realtime server-streaming push of pool states and runner counts
	WatchPools(context.Context, *connect.Request[v1.WatchPoolsRequest]) (*connect.ServerStreamForClient[v1.WatchPoolsResponse], error)
	// ListRunners lists active container instances for a pool
	ListRunners(context.Context, *connect.Request[v1.ListRunnersRequest]) (*connect.Response[v1.ListRunnersResponse], error)
	// TerminateRunner manually kills an active runner container instance
	TerminateRunner(context.Context, *connect.Request[v1.TerminateRunnerRequest]) (*connect.Response[v1.TerminateRunnerResponse], error)
	// WatchRunners provides near-realtime server-streaming push of active runner instances
	WatchRunners(context.Context, *connect.Request[v1.WatchRunnersRequest]) (*connect.ServerStreamForClient[v1.WatchRunnersResponse], error)
	// DiscoverTargets queries available repositories or organizations from an auth profile
	DiscoverTargets(context.Context, *connect.Request[v1.DiscoverTargetsRequest]) (*connect.Response[v1.DiscoverTargetsResponse], error)
}

// NewPoolServiceClient constructs a client for the supervisor.v1.PoolService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPoolServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PoolServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	poolServiceMethods := v1.File_api_proto.Services().ByName("PoolService").Methods()
	return &poolServiceClient{
		listPools: connect.NewClient[v1.ListPoolsRequest, v1.ListPoolsResponse](
			httpClient,
			baseURL+PoolServiceListPoolsProcedure,
			connect.WithSchema(poolServiceMethods.ByName("ListPools")),
			connect.WithClientOptions(opts...),
		),
		createPool: connect.NewClient[v1.CreatePoolRequest, v1.CreatePoolResponse](
			httpClient,
			baseURL+PoolServiceCreatePoolProcedure,
			connect.WithSchema(poolServiceMethods.ByName("CreatePool")),
			connect.WithClientOptions(opts...),
		),
		updatePool: connect.NewClient[v1.UpdatePoolRequest, v1.UpdatePoolResponse](
			httpClient,
			baseURL+PoolServiceUpdatePoolProcedure,
			connect.WithSchema(poolServiceMethods.ByName("UpdatePool")),
			connect.WithClientOptions(opts...),
		),
		deletePool: connect.NewClient[v1.DeletePoolRequest, v1.DeletePoolResponse](
			httpClient,
			baseURL+PoolServiceDeletePoolProcedure,
			connect.WithSchema(poolServiceMethods.ByName("DeletePool")),
			connect.WithClientOptions(opts...),
		),
		watchPools: connect.NewClient[v1.WatchPoolsRequest, v1.WatchPoolsResponse](
			httpClient,
			baseURL+PoolServiceWatchPoolsProcedure,
			connect.WithSchema(poolServiceMethods.ByName("WatchPools")),
			connect.WithClientOptions(opts...),
		),
		listRunners: connect.NewClient[v1.ListRunnersRequest, v1.ListRunnersResponse](
			httpClient,
			baseURL+PoolServiceListRunnersProcedure,
			connect.WithSchema(poolServiceMethods.ByName("ListRunners")),
			connect.WithClientOptions(opts...),
		),
		terminateRunner: connect.NewClient[v1.TerminateRunnerRequest, v1.TerminateRunnerResponse](
			httpClient,
			baseURL+PoolServiceTerminateRunnerProcedure,
			connect.WithSchema(poolServiceMethods.ByName("TerminateRunner")),
			connect.WithClientOptions(opts...),
		),
		watchRunners: connect.NewClient[v1.WatchRunnersRequest, v1.WatchRunnersResponse](
			httpClient,
			baseURL+PoolServiceWatchRunnersProcedure,
			connect.WithSchema(poolServiceMethods.ByName("WatchRunners")),
			connect.WithClientOptions(opts...),
		),
		discoverTargets: connect.NewClient[v1.DiscoverTargetsRequest, v1.DiscoverTargetsResponse](
			httpClient,
			baseURL+PoolServiceDiscoverTargetsProcedure,
			connect.WithSchema(poolServiceMethods.ByName("DiscoverTargets")),
			connect.WithClientOptions(opts...),
		),
	}
}

// poolServiceClient implements PoolServiceClient.
type poolServiceClient struct {
	listPools       *connect.Client[v1.ListPoolsRequest, v1.ListPoolsResponse]
	createPool      *connect.Client[v1.CreatePoolRequest, v1.CreatePoolResponse]
	updatePool      *connect.Client[v1.UpdatePoolRequest, v1.UpdatePoolResponse]
	deletePool      *connect.Client[v1.DeletePoolRequest, v1.DeletePoolResponse]
	watchPools      *connect.Client[v1.WatchPoolsRequest, v1.WatchPoolsResponse]
	listRunners     *connect.Client[v1.ListRunnersRequest, v1.ListRunnersResponse]
	terminateRunner *connect.Client[v1.TerminateRunnerRequest, v1.TerminateRunnerResponse]
	watchRunners    *connect.Client[v1.WatchRunnersRequest, v1.WatchRunnersResponse]
	discoverTargets *connect.Client[v1.DiscoverTargetsRequest, v1.DiscoverTargetsResponse]
}

// ListPools calls supervisor.v1.PoolService.ListPools.
func (c *poolServiceClient) ListPools(ctx context.Context, req *connect.Request[v1.ListPoolsRequest]) (*connect.Response[v1.ListPoolsResponse], error) {
	return c.listPools.CallUnary(ctx, req)
}

// CreatePool calls supervisor.v1.PoolService.CreatePool.
func (c *poolServiceClient) CreatePool(ctx context.Context, req *connect.Request[v1.CreatePoolRequest]) (*connect.Response[v1.CreatePoolResponse], error) {
	return c.createPool.CallUnary(ctx, req)
}

// UpdatePool calls supervisor.v1.PoolService.UpdatePool.
func (c *poolServiceClient) UpdatePool(ctx context.Context, req *connect.Request[v1.UpdatePoolRequest]) (*connect.Response[v1.UpdatePoolResponse], error) {
	return c.updatePool.CallUnary(ctx, req)
}

// DeletePool calls supervisor.v1.PoolService.DeletePool.
func (c *poolServiceClient) DeletePool(ctx context.Context, req *connect.Request[v1.DeletePoolRequest]) (*connect.Response[v1.DeletePoolResponse], error) {
	return c.deletePool.CallUnary(ctx, req)
}

// WatchPools calls supervisor.v1.PoolService.WatchPools.
func (c *poolServiceClient) WatchPools(ctx context.Context, req *connect.Request[v1.WatchPoolsRequest]) (*connect.ServerStreamForClient[v1.WatchPoolsResponse], error) {
	return c.watchPools.CallServerStream(ctx, req)
}

// ListRunners calls supervisor.v1.PoolService.ListRunners.
func (c *poolServiceClient) ListRunners(ctx context.Context, req *connect.Request[v1.ListRunnersRequest]) (*connect.Response[v1.ListRunnersResponse], error) {
	return c.listRunners.CallUnary(ctx, req)
}

// TerminateRunner calls supervisor.v1.PoolService.TerminateRunner.
func (c *poolServiceClient) TerminateRunner(ctx context.Context, req *connect.Request[v1.TerminateRunnerRequest]) (*connect.Response[v1.TerminateRunnerResponse], error) {
	return c.terminateRunner.CallUnary(ctx, req)
}

// WatchRunners calls supervisor.v1.PoolService.WatchRunners.
func (c *poolServiceClient) WatchRunners(ctx context.Context, req *connect.Request[v1.WatchRunnersRequest]) (*connect.ServerStreamForClient[v1.WatchRunnersResponse], error) {
	return c.watchRunners.CallServerStream(ctx, req)
}

// DiscoverTargets calls supervisor.v1.PoolService.DiscoverTargets.
func (c *poolServiceClient) DiscoverTargets(ctx context.Context, req *connect.Request[v1.DiscoverTargetsRequest]) (*connect.Response[v1.DiscoverTargetsResponse], error) {
	return c.discoverTargets.CallUnary(ctx, req)
}

// PoolServiceHandler is an implementation of the supervisor.v1.PoolService service.
type PoolServiceHandler interface {
	ListPools(context.Context, *connect.Request[v1.ListPoolsRequest]) (*connect.Response[v1.ListPoolsResponse], error)
	CreatePool(context.Context, *connect.Request[v1.CreatePoolRequest]) (*connect.Response[v1.CreatePoolResponse], error)
	UpdatePool(context.Context, *connect.Request[v1.UpdatePoolRequest]) (*connect.Response[v1.UpdatePoolResponse], error)
	DeletePool(context.Context, *connect.Request[v1.DeletePoolRequest]) (*connect.Response[v1.DeletePoolResponse], error)
	// WatchPools provides near-realtime server-streaming push of pool states and runner counts
	WatchPools(context.Context, *connect.Request[v1.WatchPoolsRequest], *connect.ServerStream[v1.WatchPoolsResponse]) error
	// ListRunners lists active container instances for a pool
	ListRunners(context.Context, *connect.Request[v1.ListRunnersRequest]) (*connect.Response[v1.ListRunnersResponse], error)
	// TerminateRunner manually kills an active runner container instance
	TerminateRunner(context.Context, *connect.Request[v1.TerminateRunnerRequest]) (*connect.Response[v1.TerminateRunnerResponse], error)
	// WatchRunners provides near-realtime server-streaming push of active runner instances
	WatchRunners(context.Context, *connect.Request[v1.WatchRunnersRequest], *connect.ServerStream[v1.WatchRunnersResponse]) error
	// DiscoverTargets queries available repositories or organizations from an auth profile
	DiscoverTargets(context.Context, *connect.Request[v1.DiscoverTargetsRequest]) (*connect.Response[v1.DiscoverTargetsResponse], error)
}

// NewPoolServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPoolServiceHandler(svc PoolServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	poolServiceMethods := v1.File_api_proto.Services().ByName("PoolService").Methods()
	poolServiceListPoolsHandler := connect.NewUnaryHandler(
		PoolServiceListPoolsProcedure,
		svc.ListPools,
		connect.WithSchema(poolServiceMethods.ByName("ListPools")),
		connect.WithHandlerOptions(opts...),
	)
	poolServiceCreatePoolHandler := connect.NewUnaryHandler(
		PoolServiceCreatePoolProcedure,
		svc.CreatePool,
		connect.WithSchema(poolServiceMethods.ByName("CreatePool")),
		connect.WithHandlerOptions(opts...),
	)
	poolServiceUpdatePoolHandler := connect.NewUnaryHandler(
		PoolServiceUpdatePoolProcedure,
		svc.UpdatePool,
		connect.WithSchema(poolServiceMethods.ByName("UpdatePool")),
		connect.WithHandlerOptions(opts...),
	)
	poolServiceDeletePoolHandler := connect.NewUnaryHandler(
		PoolServiceDeletePoolProcedure,
		svc.DeletePool,
		connect.WithSchema(poolServiceMethods.ByName("DeletePool")),
		connect.WithHandlerOptions(opts...),
	)
	poolServiceWatchPoolsHandler := connect.NewServerStreamHandler(
		PoolServiceWatchPoolsProcedure,
		svc.WatchPools,
		connect.WithSchema(poolServiceMethods.ByName("WatchPools")),
		connect.WithHandlerOptions(opts...),
	)
	poolServiceListRunnersHandler := connect.NewUnaryHandler(
		PoolServiceListRunnersProcedure,
		svc.ListRunners,
		connect.WithSchema(poolServiceMethods.ByName("ListRunners")),
		connect.WithHandlerOptions(opts...),
	)
	poolServiceTerminateRunnerHandler := connect.NewUnaryHandler(
		PoolServiceTerminateRunnerProcedure,
		svc.TerminateRunner,
		connect.WithSchema(poolServiceMethods.ByName("TerminateRunner")),
		connect.WithHandlerOptions(opts...),
	)
	poolServiceWatchRunnersHandler := connect.NewServerStreamHandler(
		PoolServiceWatchRunnersProcedure,
		svc.WatchRunners,
		connect.WithSchema(poolServiceMethods.ByName("WatchRunners")),
		connect.WithHandlerOptions(opts...),
	)
	poolServiceDiscoverTargetsHandler := connect.NewUnaryHandler(
		PoolServiceDiscoverTargetsProcedure,
		svc.DiscoverTargets,
		connect.WithSchema(poolServiceMethods.ByName("DiscoverTargets")),
		connect.WithHandlerOptions(opts...),
	)
	return "/supervisor.v1.PoolService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PoolServiceListPoolsProcedure:
			poolServiceListPoolsHandler.ServeHTTP(w, r)
		case PoolServiceCreatePoolProcedure:
			poolServiceCreatePoolHandler.ServeHTTP(w, r)
		case PoolServiceUpdatePoolProcedure:
			poolServiceUpdatePoolHandler.ServeHTTP(w, r)
		case PoolServiceDeletePoolProcedure:
			poolServiceDeletePoolHandler.ServeHTTP(w, r)
		case PoolServiceWatchPoolsProcedure:
			poolServiceWatchPoolsHandler.ServeHTTP(w, r)
		case PoolServiceListRunnersProcedure:
			poolServiceListRunnersHandler.ServeHTTP(w, r)
		case PoolServiceTerminateRunnerProcedure:
			poolServiceTerminateRunnerHandler.ServeHTTP(w, r)
		case PoolServiceWatchRunnersProcedure:
			poolServiceWatchRunnersHandler.ServeHTTP(w, r)
		case PoolServiceDiscoverTargetsProcedure:
			poolServiceDiscoverTargetsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPoolServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPoolServiceHandler struct{}

func (UnimplementedPoolServiceHandler) ListPools(context.Context, *connect.Request[v1.ListPoolsRequest]) (*connect.Response[v1.ListPoolsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.PoolService.ListPools is not implemented"))
}

func (UnimplementedPoolServiceHandler) CreatePool(context.Context, *connect.Request[v1.CreatePoolRequest]) (*connect.Response[v1.CreatePoolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.PoolService.CreatePool is not implemented"))
}

func (UnimplementedPoolServiceHandler) UpdatePool(context.Context, *connect.Request[v1.UpdatePoolRequest]) (*connect.Response[v1.UpdatePoolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.PoolService.UpdatePool is not implemented"))
}

func (UnimplementedPoolServiceHandler) DeletePool(context.Context, *connect.Request[v1.DeletePoolRequest]) (*connect.Response[v1.DeletePoolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.PoolService.DeletePool is not implemented"))
}

func (UnimplementedPoolServiceHandler) WatchPools(context.Context, *connect.Request[v1.WatchPoolsRequest], *connect.ServerStream[v1.WatchPoolsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.PoolService.WatchPools is not implemented"))
}

func (UnimplementedPoolServiceHandler) ListRunners(context.Context, *connect.Request[v1.ListRunnersRequest]) (*connect.Response[v1.ListRunnersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.PoolService.ListRunners is not implemented"))
}

func (UnimplementedPoolServiceHandler) TerminateRunner(context.Context, *connect.Request[v1.TerminateRunnerRequest]) (*connect.Response[v1.TerminateRunnerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.PoolService.TerminateRunner is not implemented"))
}

func (UnimplementedPoolServiceHandler) WatchRunners(context.Context, *connect.Request[v1.WatchRunnersRequest], *connect.ServerStream[v1.WatchRunnersResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.PoolService.WatchRunners is not implemented"))
}

func (UnimplementedPoolServiceHandler) DiscoverTargets(context.Context, *connect.Request[v1.DiscoverTargetsRequest]) (*connect.Response[v1.DiscoverTargetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.PoolService.DiscoverTargets is not implemented"))
}

// AuthProfileServiceClient is a client for the supervisor.v1.AuthProfileService service.
type AuthProfileServiceClient interface {
	ListAuthProfiles(context.Context, *connect.Request[v1.ListAuthProfilesRequest]) (*connect.Response[v1.ListAuthProfilesResponse], error)
	CreateAuthProfile(context.Context, *connect.Request[v1.CreateAuthProfileRequest]) (*connect.Response[v1.CreateAuthProfileResponse], error)
	DeleteAuthProfile(context.Context, *connect.Request[v1.DeleteAuthProfileRequest]) (*connect.Response[v1.DeleteAuthProfileResponse], error)
}

// NewAuthProfileServiceClient constructs a client for the supervisor.v1.AuthProfileService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthProfileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthProfileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authProfileServiceMethods := v1.File_api_proto.Services().ByName("AuthProfileService").Methods()
	return &authProfileServiceClient{
		listAuthProfiles: connect.NewClient[v1.ListAuthProfilesRequest, v1.ListAuthProfilesResponse](
			httpClient,
			baseURL+AuthProfileServiceListAuthProfilesProcedure,
			connect.WithSchema(authProfileServiceMethods.ByName("ListAuthProfiles")),
			connect.WithClientOptions(opts...),
		),
		createAuthProfile: connect.NewClient[v1.CreateAuthProfileRequest, v1.CreateAuthProfileResponse](
			httpClient,
			baseURL+AuthProfileServiceCreateAuthProfileProcedure,
			connect.WithSchema(authProfileServiceMethods.ByName("CreateAuthProfile")),
			connect.WithClientOptions(opts...),
		),
		deleteAuthProfile: connect.NewClient[v1.DeleteAuthProfileRequest, v1.DeleteAuthProfileResponse](
			httpClient,
			baseURL+AuthProfileServiceDeleteAuthProfileProcedure,
			connect.WithSchema(authProfileServiceMethods.ByName("DeleteAuthProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authProfileServiceClient implements AuthProfileServiceClient.
type authProfileServiceClient struct {
	listAuthProfiles  *connect.Client[v1.ListAuthProfilesRequest, v1.ListAuthProfilesResponse]
	createAuthProfile *connect.Client[v1.CreateAuthProfileRequest, v1.CreateAuthProfileResponse]
	deleteAuthProfile *connect.Client[v1.DeleteAuthProfileRequest, v1.DeleteAuthProfileResponse]
}

// ListAuthProfiles calls supervisor.v1.AuthProfileService.ListAuthProfiles.
func (c *authProfileServiceClient) ListAuthProfiles(ctx context.Context, req *connect.Request[v1.ListAuthProfilesRequest]) (*connect.Response[v1.ListAuthProfilesResponse], error) {
	return c.listAuthProfiles.CallUnary(ctx, req)
}

// CreateAuthProfile calls supervisor.v1.AuthProfileService.CreateAuthProfile.
func (c *authProfileServiceClient) CreateAuthProfile(ctx context.Context, req *connect.Request[v1.CreateAuthProfileRequest]) (*connect.Response[v1.CreateAuthProfileResponse], error) {
	return c.createAuthProfile.CallUnary(ctx, req)
}

// DeleteAuthProfile calls supervisor.v1.AuthProfileService.DeleteAuthProfile.
func (c *authProfileServiceClient) DeleteAuthProfile(ctx context.Context, req *connect.Request[v1.DeleteAuthProfileRequest]) (*connect.Response[v1.DeleteAuthProfileResponse], error) {
	return c.deleteAuthProfile.CallUnary(ctx, req)
}

// AuthProfileServiceHandler is an implementation of the supervisor.v1.AuthProfileService service.
type AuthProfileServiceHandler interface {
	ListAuthProfiles(context.Context, *connect.Request[v1.ListAuthProfilesRequest]) (*connect.Response[v1.ListAuthProfilesResponse], error)
	CreateAuthProfile(context.Context, *connect.Request[v1.CreateAuthProfileRequest]) (*connect.Response[v1.CreateAuthProfileResponse], error)
	DeleteAuthProfile(context.Context, *connect.Request[v1.DeleteAuthProfileRequest]) (*connect.Response[v1.DeleteAuthProfileResponse], error)
}

// NewAuthProfileServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthProfileServiceHandler(svc AuthProfileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authProfileServiceMethods := v1.File_api_proto.Services().ByName("AuthProfileService").Methods()
	authProfileServiceListAuthProfilesHandler := connect.NewUnaryHandler(
		AuthProfileServiceListAuthProfilesProcedure,
		svc.ListAuthProfiles,
		connect.WithSchema(authProfileServiceMethods.ByName("ListAuthProfiles")),
		connect.WithHandlerOptions(opts...),
	)
	authProfileServiceCreateAuthProfileHandler := connect.NewUnaryHandler(
		AuthProfileServiceCreateAuthProfileProcedure,
		svc.CreateAuthProfile,
		connect.WithSchema(authProfileServiceMethods.ByName("CreateAuthProfile")),
		connect.WithHandlerOptions(opts...),
	)
	authProfileServiceDeleteAuthProfileHandler := connect.NewUnaryHandler(
		AuthProfileServiceDeleteAuthProfileProcedure,
		svc.DeleteAuthProfile,
		connect.WithSchema(authProfileServiceMethods.ByName("DeleteAuthProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/supervisor.v1.AuthProfileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthProfileServiceListAuthProfilesProcedure:
			authProfileServiceListAuthProfilesHandler.ServeHTTP(w, r)
		case AuthProfileServiceCreateAuthProfileProcedure:
			authProfileServiceCreateAuthProfileHandler.ServeHTTP(w, r)
		case AuthProfileServiceDeleteAuthProfileProcedure:
			authProfileServiceDeleteAuthProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthProfileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthProfileServiceHandler struct{}

func (UnimplementedAuthProfileServiceHandler) ListAuthProfiles(context.Context, *connect.Request[v1.ListAuthProfilesRequest]) (*connect.Response[v1.ListAuthProfilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AuthProfileService.ListAuthProfiles is not implemented"))
}

func (UnimplementedAuthProfileServiceHandler) CreateAuthProfile(context.Context, *connect.Request[v1.CreateAuthProfileRequest]) (*connect.Response[v1.CreateAuthProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AuthProfileService.CreateAuthProfile is not implemented"))
}

func (UnimplementedAuthProfileServiceHandler) DeleteAuthProfile(context.Context, *connect.Request[v1.DeleteAuthProfileRequest]) (*connect.Response[v1.DeleteAuthProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AuthProfileService.DeleteAuthProfile is not implemented"))
}

// OnboardingServiceClient is a client for the supervisor.v1.OnboardingService service.
type OnboardingServiceClient interface {
	GetOnboardingStatus(context.Context, *connect.Request[v1.GetOnboardingStatusRequest]) (*connect.Response[v1.GetOnboardingStatusResponse], error)
	GetAppSettings(context.Context, *connect.Request[v1.GetAppSettingsRequest]) (*connect.Response[v1.GetAppSettingsResponse], error)
	SetAppSetting(context.Context, *connect.Request[v1.SetAppSettingRequest]) (*connect.Response[v1.SetAppSettingResponse], error)
	CompleteOnboarding(context.Context, *connect.Request[v1.CompleteOnboardingRequest]) (*connect.Response[v1.CompleteOnboardingResponse], error)
}

// NewOnboardingServiceClient constructs a client for the supervisor.v1.OnboardingService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOnboardingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OnboardingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	onboardingServiceMethods := v1.File_api_proto.Services().ByName("OnboardingService").Methods()
	return &onboardingServiceClient{
		getOnboardingStatus: connect.NewClient[v1.GetOnboardingStatusRequest, v1.GetOnboardingStatusResponse](
			httpClient,
			baseURL+OnboardingServiceGetOnboardingStatusProcedure,
			connect.WithSchema(onboardingServiceMethods.ByName("GetOnboardingStatus")),
			connect.WithClientOptions(opts...),
		),
		getAppSettings: connect.NewClient[v1.GetAppSettingsRequest, v1.GetAppSettingsResponse](
			httpClient,
			baseURL+OnboardingServiceGetAppSettingsProcedure,
			connect.WithSchema(onboardingServiceMethods.ByName("GetAppSettings")),
			connect.WithClientOptions(opts...),
		),
		setAppSetting: connect.NewClient[v1.SetAppSettingRequest, v1.SetAppSettingResponse](
			httpClient,
			baseURL+OnboardingServiceSetAppSettingProcedure,
			connect.WithSchema(onboardingServiceMethods.ByName("SetAppSetting")),
			connect.WithClientOptions(opts...),
		),
		completeOnboarding: connect.NewClient[v1.CompleteOnboardingRequest, v1.CompleteOnboardingResponse](
			httpClient,
			baseURL+OnboardingServiceCompleteOnboardingProcedure,
			connect.WithSchema(onboardingServiceMethods.ByName("CompleteOnboarding")),
			connect.WithClientOptions(opts...),
		),
	}
}

// onboardingServiceClient implements OnboardingServiceClient.
type onboardingServiceClient struct {
	getOnboardingStatus *connect.Client[v1.GetOnboardingStatusRequest, v1.GetOnboardingStatusResponse]
	getAppSettings      *connect.Client[v1.GetAppSettingsRequest, v1.GetAppSettingsResponse]
	setAppSetting       *connect.Client[v1.SetAppSettingRequest, v1.SetAppSettingResponse]
	completeOnboarding  *connect.Client[v1.CompleteOnboardingRequest, v1.CompleteOnboardingResponse]
}

// GetOnboardingStatus calls supervisor.v1.OnboardingService.GetOnboardingStatus.
func (c *onboardingServiceClient) GetOnboardingStatus(ctx context.Context, req *connect.Request[v1.GetOnboardingStatusRequest]) (*connect.Response[v1.GetOnboardingStatusResponse], error) {
	return c.getOnboardingStatus.CallUnary(ctx, req)
}

// GetAppSettings calls supervisor.v1.OnboardingService.GetAppSettings.
func (c *onboardingServiceClient) GetAppSettings(ctx context.Context, req *connect.Request[v1.GetAppSettingsRequest]) (*connect.Response[v1.GetAppSettingsResponse], error) {
	return c.getAppSettings.CallUnary(ctx, req)
}

// SetAppSetting calls supervisor.v1.OnboardingService.SetAppSetting.
func (c *onboardingServiceClient) SetAppSetting(ctx context.Context, req *connect.Request[v1.SetAppSettingRequest]) (*connect.Response[v1.SetAppSettingResponse], error) {
	return c.setAppSetting.CallUnary(ctx, req)
}

// CompleteOnboarding calls supervisor.v1.OnboardingService.CompleteOnboarding.
func (c *onboardingServiceClient) CompleteOnboarding(ctx context.Context, req *connect.Request[v1.CompleteOnboardingRequest]) (*connect.Response[v1.CompleteOnboardingResponse], error) {
	return c.completeOnboarding.CallUnary(ctx, req)
}

// OnboardingServiceHandler is an implementation of the supervisor.v1.OnboardingService service.
type OnboardingServiceHandler interface {
	GetOnboardingStatus(context.Context, *connect.Request[v1.GetOnboardingStatusRequest]) (*connect.Response[v1.GetOnboardingStatusResponse], error)
	GetAppSettings(context.Context, *connect.Request[v1.GetAppSettingsRequest]) (*connect.Response[v1.GetAppSettingsResponse], error)
	SetAppSetting(context.Context, *connect.Request[v1.SetAppSettingRequest]) (*connect.Response[v1.SetAppSettingResponse], error)
	CompleteOnboarding(context.Context, *connect.Request[v1.CompleteOnboardingRequest]) (*connect.Response[v1.CompleteOnboardingResponse], error)
}

// NewOnboardingServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOnboardingServiceHandler(svc OnboardingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	onboardingServiceMethods := v1.File_api_proto.Services().ByName("OnboardingService").Methods()
	onboardingServiceGetOnboardingStatusHandler := connect.NewUnaryHandler(
		OnboardingServiceGetOnboardingStatusProcedure,
		svc.GetOnboardingStatus,
		connect.WithSchema(onboardingServiceMethods.ByName("GetOnboardingStatus")),
		connect.WithHandlerOptions(opts...),
	)
	onboardingServiceGetAppSettingsHandler := connect.NewUnaryHandler(
		OnboardingServiceGetAppSettingsProcedure,
		svc.GetAppSettings,
		connect.WithSchema(onboardingServiceMethods.ByName("GetAppSettings")),
		connect.WithHandlerOptions(opts...),
	)
	onboardingServiceSetAppSettingHandler := connect.NewUnaryHandler(
		OnboardingServiceSetAppSettingProcedure,
		svc.SetAppSetting,
		connect.WithSchema(onboardingServiceMethods.ByName("SetAppSetting")),
		connect.WithHandlerOptions(opts...),
	)
	onboardingServiceCompleteOnboardingHandler := connect.NewUnaryHandler(
		OnboardingServiceCompleteOnboardingProcedure,
		svc.CompleteOnboarding,
		connect.WithSchema(onboardingServiceMethods.ByName("CompleteOnboarding")),
		connect.WithHandlerOptions(opts...),
	)
	return "/supervisor.v1.OnboardingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OnboardingServiceGetOnboardingStatusProcedure:
			onboardingServiceGetOnboardingStatusHandler.ServeHTTP(w, r)
		case OnboardingServiceGetAppSettingsProcedure:
			onboardingServiceGetAppSettingsHandler.ServeHTTP(w, r)
		case OnboardingServiceSetAppSettingProcedure:
			onboardingServiceSetAppSettingHandler.ServeHTTP(w, r)
		case OnboardingServiceCompleteOnboardingProcedure:
			onboardingServiceCompleteOnboardingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOnboardingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOnboardingServiceHandler struct{}

func (UnimplementedOnboardingServiceHandler) GetOnboardingStatus(context.Context, *connect.Request[v1.GetOnboardingStatusRequest]) (*connect.Response[v1.GetOnboardingStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.OnboardingService.GetOnboardingStatus is not implemented"))
}

func (UnimplementedOnboardingServiceHandler) GetAppSettings(context.Context, *connect.Request[v1.GetAppSettingsRequest]) (*connect.Response[v1.GetAppSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.OnboardingService.GetAppSettings is not implemented"))
}

func (UnimplementedOnboardingServiceHandler) SetAppSetting(context.Context, *connect.Request[v1.SetAppSettingRequest]) (*connect.Response[v1.SetAppSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.OnboardingService.SetAppSetting is not implemented"))
}

func (UnimplementedOnboardingServiceHandler) CompleteOnboarding(context.Context, *connect.Request[v1.CompleteOnboardingRequest]) (*connect.Response[v1.CompleteOnboardingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.OnboardingService.CompleteOnboarding is not implemented"))
}

// AnalyticsServiceClient is a client for the supervisor.v1.AnalyticsService service.
type AnalyticsServiceClient interface {
	GetJobHistory(context.Context, *connect.Request[v1.GetJobHistoryRequest]) (*connect.Response[v1.GetJobHistoryResponse], error)
	GetJobRecord(context.Context, *connect.Request[v1.GetJobRecordRequest]) (*connect.Response[v1.GetJobRecordResponse], error)
	GetSystemStats(context.Context, *connect.Request[v1.GetSystemStatsRequest]) (*connect.Response[v1.GetSystemStatsResponse], error)
	// WatchDashboard provides near-realtime server-streaming push of dashboard statistics, pool states, and recent jobs
	WatchDashboard(context.Context, *connect.Request[v1.WatchDashboardRequest]) (*connect.ServerStreamForClient[v1.WatchDashboardResponse], error)
}

// NewAnalyticsServiceClient constructs a client for the supervisor.v1.AnalyticsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalyticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalyticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analyticsServiceMethods := v1.File_api_proto.Services().ByName("AnalyticsService").Methods()
	return &analyticsServiceClient{
		getJobHistory: connect.NewClient[v1.GetJobHistoryRequest, v1.GetJobHistoryResponse](
			httpClient,
			baseURL+AnalyticsServiceGetJobHistoryProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetJobHistory")),
			connect.WithClientOptions(opts...),
		),
		getJobRecord: connect.NewClient[v1.GetJobRecordRequest, v1.GetJobRecordResponse](
			httpClient,
			baseURL+AnalyticsServiceGetJobRecordProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetJobRecord")),
			connect.WithClientOptions(opts...),
		),
		getSystemStats: connect.NewClient[v1.GetSystemStatsRequest, v1.GetSystemStatsResponse](
			httpClient,
			baseURL+AnalyticsServiceGetSystemStatsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetSystemStats")),
			connect.WithClientOptions(opts...),
		),
		watchDashboard: connect.NewClient[v1.WatchDashboardRequest, v1.WatchDashboardResponse](
			httpClient,
			baseURL+AnalyticsServiceWatchDashboardProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("WatchDashboard")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analyticsServiceClient implements AnalyticsServiceClient.
type analyticsServiceClient struct {
	getJobHistory  *connect.Client[v1.GetJobHistoryRequest, v1.GetJobHistoryResponse]
	getJobRecord   *connect.Client[v1.GetJobRecordRequest, v1.GetJobRecordResponse]
	getSystemStats *connect.Client[v1.GetSystemStatsRequest, v1.GetSystemStatsResponse]
	watchDashboard *connect.Client[v1.WatchDashboardRequest, v1.WatchDashboardResponse]
}

// GetJobHistory calls supervisor.v1.AnalyticsService.GetJobHistory.
func (c *analyticsServiceClient) GetJobHistory(ctx context.Context, req *connect.Request[v1.GetJobHistoryRequest]) (*connect.Response[v1.GetJobHistoryResponse], error) {
	return c.getJobHistory.CallUnary(ctx, req)
}

// GetJobRecord calls supervisor.v1.AnalyticsService.GetJobRecord.
func (c *analyticsServiceClient) GetJobRecord(ctx context.Context, req *connect.Request[v1.GetJobRecordRequest]) (*connect.Response[v1.GetJobRecordResponse], error) {
	return c.getJobRecord.CallUnary(ctx, req)
}

// GetSystemStats calls supervisor.v1.AnalyticsService.GetSystemStats.
func (c *analyticsServiceClient) GetSystemStats(ctx context.Context, req *connect.Request[v1.GetSystemStatsRequest]) (*connect.Response[v1.GetSystemStatsResponse], error) {
	return c.getSystemStats.CallUnary(ctx, req)
}

// WatchDashboard calls supervisor.v1.AnalyticsService.WatchDashboard.
func (c *analyticsServiceClient) WatchDashboard(ctx context.Context, req *connect.Request[v1.WatchDashboardRequest]) (*connect.ServerStreamForClient[v1.WatchDashboardResponse], error) {
	return c.watchDashboard.CallServerStream(ctx, req)
}

// AnalyticsServiceHandler is an implementation of the supervisor.v1.AnalyticsService service.
type AnalyticsServiceHandler interface {
	GetJobHistory(context.Context, *connect.Request[v1.GetJobHistoryRequest]) (*connect.Response[v1.GetJobHistoryResponse], error)
	GetJobRecord(context.Context, *connect.Request[v1.GetJobRecordRequest]) (*connect.Response[v1.GetJobRecordResponse], error)
	GetSystemStats(context.Context, *connect.Request[v1.GetSystemStatsRequest]) (*connect.Response[v1.GetSystemStatsResponse], error)
	// WatchDashboard provides near-realtime server-streaming push of dashboard statistics, pool states, and recent jobs
	WatchDashboard(context.Context, *connect.Request[v1.WatchDashboardRequest], *connect.ServerStream[v1.WatchDashboardResponse]) error
}

// NewAnalyticsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalyticsServiceHandler(svc AnalyticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analyticsServiceMethods := v1.File_api_proto.Services().ByName("AnalyticsService").Methods()
	analyticsServiceGetJobHistoryHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetJobHistoryProcedure,
		svc.GetJobHistory,
		connect.WithSchema(analyticsServiceMethods.ByName("GetJobHistory")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetJobRecordHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetJobRecordProcedure,
		svc.GetJobRecord,
		connect.WithSchema(analyticsServiceMethods.ByName("GetJobRecord")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetSystemStatsHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetSystemStatsProcedure,
		svc.GetSystemStats,
		connect.WithSchema(analyticsServiceMethods.ByName("GetSystemStats")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceWatchDashboardHandler := connect.NewServerStreamHandler(
		AnalyticsServiceWatchDashboardProcedure,
		svc.WatchDashboard,
		connect.WithSchema(analyticsServiceMethods.ByName("WatchDashboard")),
		connect.WithHandlerOptions(opts...),
	)
	return "/supervisor.v1.AnalyticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalyticsServiceGetJobHistoryProcedure:
			analyticsServiceGetJobHistoryHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetJobRecordProcedure:
			analyticsServiceGetJobRecordHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetSystemStatsProcedure:
			analyticsServiceGetSystemStatsHandler.ServeHTTP(w, r)
		case AnalyticsServiceWatchDashboardProcedure:
			analyticsServiceWatchDashboardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalyticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalyticsServiceHandler struct{}

func (UnimplementedAnalyticsServiceHandler) GetJobHistory(context.Context, *connect.Request[v1.GetJobHistoryRequest]) (*connect.Response[v1.GetJobHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AnalyticsService.GetJobHistory is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetJobRecord(context.Context, *connect.Request[v1.GetJobRecordRequest]) (*connect.Response[v1.GetJobRecordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AnalyticsService.GetJobRecord is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetSystemStats(context.Context, *connect.Request[v1.GetSystemStatsRequest]) (*connect.Response[v1.GetSystemStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AnalyticsService.GetSystemStats is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) WatchDashboard(context.Context, *connect.Request[v1.WatchDashboardRequest], *connect.ServerStream[v1.WatchDashboardResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.AnalyticsService.WatchDashboard is not implemented"))
}

// LogServiceClient is a client for the supervisor.v1.LogService service.
type LogServiceClient interface {
	// Live streaming logs of an active runner container
	StreamRunnerLogs(context.Context, *connect.Request[v1.StreamRunnerLogsRequest]) (*connect.ServerStreamForClient[v1.LogChunk], error)
	// Historical logs for completed/exited runners
	GetRunnerLogs(context.Context, *connect.Request[v1.GetRunnerLogsRequest]) (*connect.Response[v1.GetRunnerLogsResponse], error)
}

// NewLogServiceClient constructs a client for the supervisor.v1.LogService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	logServiceMethods := v1.File_api_proto.Services().ByName("LogService").Methods()
	return &logServiceClient{
		streamRunnerLogs: connect.NewClient[v1.StreamRunnerLogsRequest, v1.LogChunk](
			httpClient,
			baseURL+LogServiceStreamRunnerLogsProcedure,
			connect.WithSchema(logServiceMethods.ByName("StreamRunnerLogs")),
			connect.WithClientOptions(opts...),
		),
		getRunnerLogs: connect.NewClient[v1.GetRunnerLogsRequest, v1.GetRunnerLogsResponse](
			httpClient,
			baseURL+LogServiceGetRunnerLogsProcedure,
			connect.WithSchema(logServiceMethods.ByName("GetRunnerLogs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// logServiceClient implements LogServiceClient.
type logServiceClient struct {
	streamRunnerLogs *connect.Client[v1.StreamRunnerLogsRequest, v1.LogChunk]
	getRunnerLogs    *connect.Client[v1.GetRunnerLogsRequest, v1.GetRunnerLogsResponse]
}

// StreamRunnerLogs calls supervisor.v1.LogService.StreamRunnerLogs.
func (c *logServiceClient) StreamRunnerLogs(ctx context.Context, req *connect.Request[v1.StreamRunnerLogsRequest]) (*connect.ServerStreamForClient[v1.LogChunk], error) {
	return c.streamRunnerLogs.CallServerStream(ctx, req)
}

// GetRunnerLogs calls supervisor.v1.LogService.GetRunnerLogs.
func (c *logServiceClient) GetRunnerLogs(ctx context.Context, req *connect.Request[v1.GetRunnerLogsRequest]) (*connect.Response[v1.GetRunnerLogsResponse], error) {
	return c.getRunnerLogs.CallUnary(ctx, req)
}

// LogServiceHandler is an implementation of the supervisor.v1.LogService service.
type LogServiceHandler interface {
	// Live streaming logs of an active runner container
	StreamRunnerLogs(context.Context, *connect.Request[v1.StreamRunnerLogsRequest], *connect.ServerStream[v1.LogChunk]) error
	// Historical logs for completed/exited runners
	GetRunnerLogs(context.Context, *connect.Request[v1.GetRunnerLogsRequest]) (*connect.Response[v1.GetRunnerLogsResponse], error)
}

// NewLogServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLogServiceHandler(svc LogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	logServiceMethods := v1.File_api_proto.Services().ByName("LogService").Methods()
	logServiceStreamRunnerLogsHandler := connect.NewServerStreamHandler(
		LogServiceStreamRunnerLogsProcedure,
		svc.StreamRunnerLogs,
		connect.WithSchema(logServiceMethods.ByName("StreamRunnerLogs")),
		connect.WithHandlerOptions(opts...),
	)
	logServiceGetRunnerLogsHandler := connect.NewUnaryHandler(
		LogServiceGetRunnerLogsProcedure,
		svc.GetRunnerLogs,
		connect.WithSchema(logServiceMethods.ByName("GetRunnerLogs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/supervisor.v1.LogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LogServiceStreamRunnerLogsProcedure:
			logServiceStreamRunnerLogsHandler.ServeHTTP(w, r)
		case LogServiceGetRunnerLogsProcedure:
			logServiceGetRunnerLogsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLogServiceHandler struct{}

func (UnimplementedLogServiceHandler) StreamRunnerLogs(context.Context, *connect.Request[v1.StreamRunnerLogsRequest], *connect.ServerStream[v1.LogChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.LogService.StreamRunnerLogs is not implemented"))
}

func (UnimplementedLogServiceHandler) GetRunnerLogs(context.Context, *connect.Request[v1.GetRunnerLogsRequest]) (*connect.Response[v1.GetRunnerLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.LogService.GetRunnerLogs is not implemented"))
}

// RenovateServiceClient is a client for the supervisor.v1.RenovateService service.
type RenovateServiceClient interface {
	// Manually trigger a Renovate run for a pool
	TriggerRenovateRun(context.Context, *connect.Request[v1.TriggerRenovateRunRequest]) (*connect.Response[v1.TriggerRenovateRunResponse], error)
	// Get current status of Renovate runs for a pool
	GetRenovateStatus(context.Context, *connect.Request[v1.GetRenovateStatusRequest]) (*connect.Response[v1.GetRenovateStatusResponse], error)
	// List historical Renovate runs
	ListRenovateHistory(context.Context, *connect.Request[v1.ListRenovateHistoryRequest]) (*connect.Response[v1.ListRenovateHistoryResponse], error)
}

// NewRenovateServiceClient constructs a client for the supervisor.v1.RenovateService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRenovateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RenovateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	renovateServiceMethods := v1.File_api_proto.Services().ByName("RenovateService").Methods()
	return &renovateServiceClient{
		triggerRenovateRun: connect.NewClient[v1.TriggerRenovateRunRequest, v1.TriggerRenovateRunResponse](
			httpClient,
			baseURL+RenovateServiceTriggerRenovateRunProcedure,
			connect.WithSchema(renovateServiceMethods.ByName("TriggerRenovateRun")),
			connect.WithClientOptions(opts...),
		),
		getRenovateStatus: connect.NewClient[v1.GetRenovateStatusRequest, v1.GetRenovateStatusResponse](
			httpClient,
			baseURL+RenovateServiceGetRenovateStatusProcedure,
			connect.WithSchema(renovateServiceMethods.ByName("GetRenovateStatus")),
			connect.WithClientOptions(opts...),
		),
		listRenovateHistory: connect.NewClient[v1.ListRenovateHistoryRequest, v1.ListRenovateHistoryResponse](
			httpClient,
			baseURL+RenovateServiceListRenovateHistoryProcedure,
			connect.WithSchema(renovateServiceMethods.ByName("ListRenovateHistory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// renovateServiceClient implements RenovateServiceClient.
type renovateServiceClient struct {
	triggerRenovateRun  *connect.Client[v1.TriggerRenovateRunRequest, v1.TriggerRenovateRunResponse]
	getRenovateStatus   *connect.Client[v1.GetRenovateStatusRequest, v1.GetRenovateStatusResponse]
	listRenovateHistory *connect.Client[v1.ListRenovateHistoryRequest, v1.ListRenovateHistoryResponse]
}

// TriggerRenovateRun calls supervisor.v1.RenovateService.TriggerRenovateRun.
func (c *renovateServiceClient) TriggerRenovateRun(ctx context.Context, req *connect.Request[v1.TriggerRenovateRunRequest]) (*connect.Response[v1.TriggerRenovateRunResponse], error) {
	return c.triggerRenovateRun.CallUnary(ctx, req)
}

// GetRenovateStatus calls supervisor.v1.RenovateService.GetRenovateStatus.
func (c *renovateServiceClient) GetRenovateStatus(ctx context.Context, req *connect.Request[v1.GetRenovateStatusRequest]) (*connect.Response[v1.GetRenovateStatusResponse], error) {
	return c.getRenovateStatus.CallUnary(ctx, req)
}

// ListRenovateHistory calls supervisor.v1.RenovateService.ListRenovateHistory.
func (c *renovateServiceClient) ListRenovateHistory(ctx context.Context, req *connect.Request[v1.ListRenovateHistoryRequest]) (*connect.Response[v1.ListRenovateHistoryResponse], error) {
	return c.listRenovateHistory.CallUnary(ctx, req)
}

// RenovateServiceHandler is an implementation of the supervisor.v1.RenovateService service.
type RenovateServiceHandler interface {
	// Manually trigger a Renovate run for a pool
	TriggerRenovateRun(context.Context, *connect.Request[v1.TriggerRenovateRunRequest]) (*connect.Response[v1.TriggerRenovateRunResponse], error)
	// Get current status of Renovate runs for a pool
	GetRenovateStatus(context.Context, *connect.Request[v1.GetRenovateStatusRequest]) (*connect.Response[v1.GetRenovateStatusResponse], error)
	// List historical Renovate runs
	ListRenovateHistory(context.Context, *connect.Request[v1.ListRenovateHistoryRequest]) (*connect.Response[v1.ListRenovateHistoryResponse], error)
}

// NewRenovateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRenovateServiceHandler(svc RenovateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	renovateServiceMethods := v1.File_api_proto.Services().ByName("RenovateService").Methods()
	renovateServiceTriggerRenovateRunHandler := connect.NewUnaryHandler(
		RenovateServiceTriggerRenovateRunProcedure,
		svc.TriggerRenovateRun,
		connect.WithSchema(renovateServiceMethods.ByName("TriggerRenovateRun")),
		connect.WithHandlerOptions(opts...),
	)
	renovateServiceGetRenovateStatusHandler := connect.NewUnaryHandler(
		RenovateServiceGetRenovateStatusProcedure,
		svc.GetRenovateStatus,
		connect.WithSchema(renovateServiceMethods.ByName("GetRenovateStatus")),
		connect.WithHandlerOptions(opts...),
	)
	renovateServiceListRenovateHistoryHandler := connect.NewUnaryHandler(
		RenovateServiceListRenovateHistoryProcedure,
		svc.ListRenovateHistory,
		connect.WithSchema(renovateServiceMethods.ByName("ListRenovateHistory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/supervisor.v1.RenovateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RenovateServiceTriggerRenovateRunProcedure:
			renovateServiceTriggerRenovateRunHandler.ServeHTTP(w, r)
		case RenovateServiceGetRenovateStatusProcedure:
			renovateServiceGetRenovateStatusHandler.ServeHTTP(w, r)
		case RenovateServiceListRenovateHistoryProcedure:
			renovateServiceListRenovateHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRenovateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRenovateServiceHandler struct{}

func (UnimplementedRenovateServiceHandler) TriggerRenovateRun(context.Context, *connect.Request[v1.TriggerRenovateRunRequest]) (*connect.Response[v1.TriggerRenovateRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.RenovateService.TriggerRenovateRun is not implemented"))
}

func (UnimplementedRenovateServiceHandler) GetRenovateStatus(context.Context, *connect.Request[v1.GetRenovateStatusRequest]) (*connect.Response[v1.GetRenovateStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.RenovateService.GetRenovateStatus is not implemented"))
}

func (UnimplementedRenovateServiceHandler) ListRenovateHistory(context.Context, *connect.Request[v1.ListRenovateHistoryRequest]) (*connect.Response[v1.ListRenovateHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.RenovateService.ListRenovateHistory is not implemented"))
}

// ImageUpdateServiceClient is a client for the supervisor.v1.ImageUpdateService service.
type ImageUpdateServiceClient interface {
	// Check whether a newer image is available for a pool
	CheckImageUpdate(context.Context, *connect.Request[v1.CheckImageUpdateRequest]) (*connect.Response[v1.CheckImageUpdateResponse], error)
	// Manually trigger pulling updated image
	PullImage(context.Context, *connect.Request[v1.PullImageRequest]) (*connect.Response[v1.PullImageResponse], error)
	// List pending image updates across pools
	ListImageUpdates(context.Context, *connect.Request[v1.ListImageUpdatesRequest]) (*connect.Response[v1.ListImageUpdatesResponse], error)
	// Acknowledge / dismiss an image update notification
	DismissImageUpdate(context.Context, *connect.Request[v1.DismissImageUpdateRequest]) (*connect.Response[v1.DismissImageUpdateResponse], error)
}

// NewImageUpdateServiceClient constructs a client for the supervisor.v1.ImageUpdateService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewImageUpdateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ImageUpdateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	imageUpdateServiceMethods := v1.File_api_proto.Services().ByName("ImageUpdateService").Methods()
	return &imageUpdateServiceClient{
		checkImageUpdate: connect.NewClient[v1.CheckImageUpdateRequest, v1.CheckImageUpdateResponse](
			httpClient,
			baseURL+ImageUpdateServiceCheckImageUpdateProcedure,
			connect.WithSchema(imageUpdateServiceMethods.ByName("CheckImageUpdate")),
			connect.WithClientOptions(opts...),
		),
		pullImage: connect.NewClient[v1.PullImageRequest, v1.PullImageResponse](
			httpClient,
			baseURL+ImageUpdateServicePullImageProcedure,
			connect.WithSchema(imageUpdateServiceMethods.ByName("PullImage")),
			connect.WithClientOptions(opts...),
		),
		listImageUpdates: connect.NewClient[v1.ListImageUpdatesRequest, v1.ListImageUpdatesResponse](
			httpClient,
			baseURL+ImageUpdateServiceListImageUpdatesProcedure,
			connect.WithSchema(imageUpdateServiceMethods.ByName("ListImageUpdates")),
			connect.WithClientOptions(opts...),
		),
		dismissImageUpdate: connect.NewClient[v1.DismissImageUpdateRequest, v1.DismissImageUpdateResponse](
			httpClient,
			baseURL+ImageUpdateServiceDismissImageUpdateProcedure,
			connect.WithSchema(imageUpdateServiceMethods.ByName("DismissImageUpdate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// imageUpdateServiceClient implements ImageUpdateServiceClient.
type imageUpdateServiceClient struct {
	checkImageUpdate   *connect.Client[v1.CheckImageUpdateRequest, v1.CheckImageUpdateResponse]
	pullImage          *connect.Client[v1.PullImageRequest, v1.PullImageResponse]
	listImageUpdates   *connect.Client[v1.ListImageUpdatesRequest, v1.ListImageUpdatesResponse]
	dismissImageUpdate *connect.Client[v1.DismissImageUpdateRequest, v1.DismissImageUpdateResponse]
}

// CheckImageUpdate calls supervisor.v1.ImageUpdateService.CheckImageUpdate.
func (c *imageUpdateServiceClient) CheckImageUpdate(ctx context.Context, req *connect.Request[v1.CheckImageUpdateRequest]) (*connect.Response[v1.CheckImageUpdateResponse], error) {
	return c.checkImageUpdate.CallUnary(ctx, req)
}

// PullImage calls supervisor.v1.ImageUpdateService.PullImage.
func (c *imageUpdateServiceClient) PullImage(ctx context.Context, req *connect.Request[v1.PullImageRequest]) (*connect.Response[v1.PullImageResponse], error) {
	return c.pullImage.CallUnary(ctx, req)
}

// ListImageUpdates calls supervisor.v1.ImageUpdateService.ListImageUpdates.
func (c *imageUpdateServiceClient) ListImageUpdates(ctx context.Context, req *connect.Request[v1.ListImageUpdatesRequest]) (*connect.Response[v1.ListImageUpdatesResponse], error) {
	return c.listImageUpdates.CallUnary(ctx, req)
}

// DismissImageUpdate calls supervisor.v1.ImageUpdateService.DismissImageUpdate.
func (c *imageUpdateServiceClient) DismissImageUpdate(ctx context.Context, req *connect.Request[v1.DismissImageUpdateRequest]) (*connect.Response[v1.DismissImageUpdateResponse], error) {
	return c.dismissImageUpdate.CallUnary(ctx, req)
}

// ImageUpdateServiceHandler is an implementation of the supervisor.v1.ImageUpdateService service.
type ImageUpdateServiceHandler interface {
	// Check whether a newer image is available for a pool
	CheckImageUpdate(context.Context, *connect.Request[v1.CheckImageUpdateRequest]) (*connect.Response[v1.CheckImageUpdateResponse], error)
	// Manually trigger pulling updated image
	PullImage(context.Context, *connect.Request[v1.PullImageRequest]) (*connect.Response[v1.PullImageResponse], error)
	// List pending image updates across pools
	ListImageUpdates(context.Context, *connect.Request[v1.ListImageUpdatesRequest]) (*connect.Response[v1.ListImageUpdatesResponse], error)
	// Acknowledge / dismiss an image update notification
	DismissImageUpdate(context.Context, *connect.Request[v1.DismissImageUpdateRequest]) (*connect.Response[v1.DismissImageUpdateResponse], error)
}

// NewImageUpdateServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewImageUpdateServiceHandler(svc ImageUpdateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	imageUpdateServiceMethods := v1.File_api_proto.Services().ByName("ImageUpdateService").Methods()
	imageUpdateServiceCheckImageUpdateHandler := connect.NewUnaryHandler(
		ImageUpdateServiceCheckImageUpdateProcedure,
		svc.CheckImageUpdate,
		connect.WithSchema(imageUpdateServiceMethods.ByName("CheckImageUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	imageUpdateServicePullImageHandler := connect.NewUnaryHandler(
		ImageUpdateServicePullImageProcedure,
		svc.PullImage,
		connect.WithSchema(imageUpdateServiceMethods.ByName("PullImage")),
		connect.WithHandlerOptions(opts...),
	)
	imageUpdateServiceListImageUpdatesHandler := connect.NewUnaryHandler(
		ImageUpdateServiceListImageUpdatesProcedure,
		svc.ListImageUpdates,
		connect.WithSchema(imageUpdateServiceMethods.ByName("ListImageUpdates")),
		connect.WithHandlerOptions(opts...),
	)
	imageUpdateServiceDismissImageUpdateHandler := connect.NewUnaryHandler(
		ImageUpdateServiceDismissImageUpdateProcedure,
		svc.DismissImageUpdate,
		connect.WithSchema(imageUpdateServiceMethods.ByName("DismissImageUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/supervisor.v1.ImageUpdateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ImageUpdateServiceCheckImageUpdateProcedure:
			imageUpdateServiceCheckImageUpdateHandler.ServeHTTP(w, r)
		case ImageUpdateServicePullImageProcedure:
			imageUpdateServicePullImageHandler.ServeHTTP(w, r)
		case ImageUpdateServiceListImageUpdatesProcedure:
			imageUpdateServiceListImageUpdatesHandler.ServeHTTP(w, r)
		case ImageUpdateServiceDismissImageUpdateProcedure:
			imageUpdateServiceDismissImageUpdateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedImageUpdateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedImageUpdateServiceHandler struct{}

func (UnimplementedImageUpdateServiceHandler) CheckImageUpdate(context.Context, *connect.Request[v1.CheckImageUpdateRequest]) (*connect.Response[v1.CheckImageUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.ImageUpdateService.CheckImageUpdate is not implemented"))
}

func (UnimplementedImageUpdateServiceHandler) PullImage(context.Context, *connect.Request[v1.PullImageRequest]) (*connect.Response[v1.PullImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.ImageUpdateService.PullImage is not implemented"))
}

func (UnimplementedImageUpdateServiceHandler) ListImageUpdates(context.Context, *connect.Request[v1.ListImageUpdatesRequest]) (*connect.Response[v1.ListImageUpdatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.ImageUpdateService.ListImageUpdates is not implemented"))
}

func (UnimplementedImageUpdateServiceHandler) DismissImageUpdate(context.Context, *connect.Request[v1.DismissImageUpdateRequest]) (*connect.Response[v1.DismissImageUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("supervisor.v1.ImageUpdateService.DismissImageUpdate is not implemented"))
}
