// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_users.sql

package db

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (
    username,
    password_hash
) VALUES (
    ?, ?
) RETURNING id, username, password_hash, created_at, updated_at, role
`

type CreateAdminUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser, arg.Username, arg.PasswordHash)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const deleteAdminUser = `-- name: DeleteAdminUser :exec
DELETE FROM admin_users
WHERE id = ?
`

func (q *Queries) DeleteAdminUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAdminUser, id)
	return err
}

const getAdminUserById = `-- name: GetAdminUserById :one
SELECT id, username, password_hash, created_at, updated_at, role FROM admin_users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAdminUserById(ctx context.Context, id int64) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserById, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, password_hash, created_at, updated_at, role FROM admin_users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, username, password_hash, created_at, updated_at, role FROM admin_users
ORDER BY id ASC
`

func (q *Queries) ListAdminUsers(ctx context.Context) ([]AdminUser, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUser{}
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminPassword = `-- name: UpdateAdminPassword :one
UPDATE admin_users
SET password_hash = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, password_hash, created_at, updated_at, role
`

type UpdateAdminPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, updateAdminPassword, arg.PasswordHash, arg.ID)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}
