// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    user_id,
    action,
    resource_type,
    resource_id,
    details,
    source_ip
) VALUES (
    ?, ?, ?, ?, ?, ?
) RETURNING id, user_id, "action", resource_type, resource_id, details, created_at, source_ip
`

type CreateAuditLogParams struct {
	UserID       sql.NullInt64  `json:"user_id"`
	Action       string         `json:"action"`
	ResourceType sql.NullString `json:"resource_type"`
	ResourceID   sql.NullInt64  `json:"resource_id"`
	Details      sql.NullString `json:"details"`
	SourceIp     sql.NullString `json:"source_ip"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
		arg.SourceIp,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.CreatedAt,
		&i.SourceIp,
	)
	return i, err
}

const getAuditLogById = `-- name: GetAuditLogById :one
SELECT id, user_id, "action", resource_type, resource_id, details, created_at, source_ip FROM audit_logs
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAuditLogById(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditLogById, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.CreatedAt,
		&i.SourceIp,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, "action", resource_type, resource_id, details, created_at, source_ip FROM audit_logs
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.CreatedAt,
			&i.SourceIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUserId = `-- name: ListAuditLogsByUserId :many
SELECT id, user_id, "action", resource_type, resource_id, details, created_at, source_ip FROM audit_logs
WHERE user_id = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByUserIdParams struct {
	UserID sql.NullInt64 `json:"user_id"`
	Limit  int64         `json:"limit"`
	Offset int64         `json:"offset"`
}

func (q *Queries) ListAuditLogsByUserId(ctx context.Context, arg ListAuditLogsByUserIdParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.CreatedAt,
			&i.SourceIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAuditLogsOlderThan = `-- name: PurgeAuditLogsOlderThan :execrows
DELETE FROM audit_logs
WHERE created_at < ?
`

// Hourly maintenance (docs/32 section 5.2): enforce the audit retention
// horizon (default 90d).
func (q *Queries) PurgeAuditLogsOlderThan(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeAuditLogsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
