// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_history.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const closeAllOpenJobsInterrupted = `-- name: CloseAllOpenJobsInterrupted :execrows
UPDATE job_history
SET completed_at = ?,
    status = 'interrupted'
WHERE completed_at IS NULL
`

func (q *Queries) CloseAllOpenJobsInterrupted(ctx context.Context, completedAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeAllOpenJobsInterrupted, completedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeOpenJobRow = `-- name: CloseOpenJobRow :execrows
UPDATE job_history
SET completed_at = ?,
    status = ?,
    log_retention_path = ?
WHERE pool_id = ?
  AND runner_name = ?
  AND completed_at IS NULL
`

type CloseOpenJobRowParams struct {
	CompletedAt      sql.NullTime   `json:"completed_at"`
	Status           string         `json:"status"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
	PoolID           int64          `json:"pool_id"`
	RunnerName       string         `json:"runner_name"`
}

func (q *Queries) CloseOpenJobRow(ctx context.Context, arg CloseOpenJobRowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeOpenJobRow,
		arg.CompletedAt,
		arg.Status,
		arg.LogRetentionPath,
		arg.PoolID,
		arg.RunnerName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeStaleOpenJobsSince = `-- name: CloseStaleOpenJobsSince :execrows
UPDATE job_history
SET completed_at = ?,
    status = 'interrupted'
WHERE completed_at IS NULL
  AND started_at IS NOT NULL
  AND started_at < ?
  AND pool_id = ?
`

type CloseStaleOpenJobsSinceParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	StartedAt   sql.NullTime `json:"started_at"`
	PoolID      int64        `json:"pool_id"`
}

func (q *Queries) CloseStaleOpenJobsSince(ctx context.Context, arg CloseStaleOpenJobsSinceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeStaleOpenJobsSince, arg.CompletedAt, arg.StartedAt, arg.PoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countJobHistory = `-- name: CountJobHistory :one
SELECT COUNT(*) FROM job_history
`

func (q *Queries) CountJobHistory(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobHistory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobHistoryByPoolId = `-- name: CountJobHistoryByPoolId :one
SELECT COUNT(*) FROM job_history
WHERE pool_id = ?
`

func (q *Queries) CountJobHistoryByPoolId(ctx context.Context, poolID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobHistoryByPoolId, poolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchJobHistory = `-- name: CountSearchJobHistory :one
SELECT COUNT(*) FROM job_history
WHERE (?1 = 0 OR pool_id = ?1)
  AND (?2 = '' OR runner_name LIKE '%' || ?2 || '%')
  AND (?3 = '' OR status = ?3)
`

type CountSearchJobHistoryParams struct {
	PoolID interface{} `json:"pool_id"`
	Search interface{} `json:"search"`
	Status interface{} `json:"status"`
}

func (q *Queries) CountSearchJobHistory(ctx context.Context, arg CountSearchJobHistoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchJobHistory, arg.PoolID, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJobHistory = `-- name: CreateJobHistory :one
INSERT INTO job_history (
    pool_id,
    runner_name,
    status,
    queued_at,
    started_at,
    completed_at,
    log_retention_path,
    source
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at
`

type CreateJobHistoryParams struct {
	PoolID           int64          `json:"pool_id"`
	RunnerName       string         `json:"runner_name"`
	Status           string         `json:"status"`
	QueuedAt         sql.NullTime   `json:"queued_at"`
	StartedAt        sql.NullTime   `json:"started_at"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
	Source           string         `json:"source"`
}

func (q *Queries) CreateJobHistory(ctx context.Context, arg CreateJobHistoryParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, createJobHistory,
		arg.PoolID,
		arg.RunnerName,
		arg.Status,
		arg.QueuedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.LogRetentionPath,
		arg.Source,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.JobID,
		&i.RunID,
		&i.WorkflowName,
		&i.HeadBranch,
		&i.HeadSha,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJobHistoryOlderThan = `-- name: DeleteJobHistoryOlderThan :exec
DELETE FROM job_history
WHERE completed_at < ?
`

func (q *Queries) DeleteJobHistoryOlderThan(ctx context.Context, completedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteJobHistoryOlderThan, completedAt)
	return err
}

const getHourlyJobStatsSince = `-- name: GetHourlyJobStatsSince :many
SELECT
    strftime('%Y-%m-%dT%H:00:00Z', created_at) as bucket_hour,
    COUNT(*) as total_jobs,
    COALESCE(SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END), 0) as successful_jobs,
    COALESCE(SUM(CASE WHEN status = 'failure' OR status = 'failed' THEN 1 ELSE 0 END), 0) as failed_jobs,
    COALESCE(SUM(CASE WHEN status IN ('success', 'failure', 'cancelled', 'timeout') THEN 1 ELSE 0 END), 0) as known_outcome_jobs,
    COALESCE(SUM(CASE WHEN queued_at IS NOT NULL THEN 1 ELSE 0 END), 0) as queue_timed_jobs,
    COALESCE(AVG(CASE WHEN started_at IS NOT NULL AND queued_at IS NOT NULL THEN (CAST(strftime('%s', replace(substr(started_at, 1, 19), 'T', ' ')) AS REAL) - CAST(strftime('%s', replace(substr(queued_at, 1, 19), 'T', ' ')) AS REAL)) END), 0.0) as avg_queue_seconds,
    COALESCE(AVG(CASE WHEN completed_at IS NOT NULL AND started_at IS NOT NULL THEN (CAST(strftime('%s', replace(substr(completed_at, 1, 19), 'T', ' ')) AS REAL) - CAST(strftime('%s', replace(substr(started_at, 1, 19), 'T', ' ')) AS REAL)) END), 0.0) as avg_runtime_seconds
FROM job_history
WHERE created_at >= ?
GROUP BY bucket_hour
ORDER BY bucket_hour ASC
`

type GetHourlyJobStatsSinceRow struct {
	BucketHour        interface{} `json:"bucket_hour"`
	TotalJobs         int64       `json:"total_jobs"`
	SuccessfulJobs    interface{} `json:"successful_jobs"`
	FailedJobs        interface{} `json:"failed_jobs"`
	KnownOutcomeJobs  interface{} `json:"known_outcome_jobs"`
	QueueTimedJobs    interface{} `json:"queue_timed_jobs"`
	AvgQueueSeconds   interface{} `json:"avg_queue_seconds"`
	AvgRuntimeSeconds interface{} `json:"avg_runtime_seconds"`
}

func (q *Queries) GetHourlyJobStatsSince(ctx context.Context, createdAt time.Time) ([]GetHourlyJobStatsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, getHourlyJobStatsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHourlyJobStatsSinceRow{}
	for rows.Next() {
		var i GetHourlyJobStatsSinceRow
		if err := rows.Scan(
			&i.BucketHour,
			&i.TotalJobs,
			&i.SuccessfulJobs,
			&i.FailedJobs,
			&i.KnownOutcomeJobs,
			&i.QueueTimedJobs,
			&i.AvgQueueSeconds,
			&i.AvgRuntimeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobHistoryById = `-- name: GetJobHistoryById :one
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at FROM job_history
WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobHistoryById(ctx context.Context, id int64) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, getJobHistoryById, id)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.JobID,
		&i.RunID,
		&i.WorkflowName,
		&i.HeadBranch,
		&i.HeadSha,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getJobStatsSince = `-- name: GetJobStatsSince :one
SELECT
    COUNT(*) as total_jobs,
    COALESCE(SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END), 0) as successful_jobs,
    COALESCE(SUM(CASE WHEN status = 'failure' OR status = 'failed' THEN 1 ELSE 0 END), 0) as failed_jobs,
    COALESCE(SUM(CASE WHEN status IN ('success', 'failure', 'cancelled', 'timeout') THEN 1 ELSE 0 END), 0) as known_outcome_jobs,
    COALESCE(SUM(CASE WHEN queued_at IS NOT NULL THEN 1 ELSE 0 END), 0) as queue_timed_jobs,
    COALESCE(AVG(CASE WHEN started_at IS NOT NULL AND queued_at IS NOT NULL THEN (CAST(strftime('%s', replace(substr(started_at, 1, 19), 'T', ' ')) AS REAL) - CAST(strftime('%s', replace(substr(queued_at, 1, 19), 'T', ' ')) AS REAL)) END), 0.0) as avg_queue_seconds,
    COALESCE(AVG(CASE WHEN completed_at IS NOT NULL AND started_at IS NOT NULL THEN (CAST(strftime('%s', replace(substr(completed_at, 1, 19), 'T', ' ')) AS REAL) - CAST(strftime('%s', replace(substr(started_at, 1, 19), 'T', ' ')) AS REAL)) END), 0.0) as avg_runtime_seconds
FROM job_history
WHERE created_at >= ?
`

type GetJobStatsSinceRow struct {
	TotalJobs         int64       `json:"total_jobs"`
	SuccessfulJobs    interface{} `json:"successful_jobs"`
	FailedJobs        interface{} `json:"failed_jobs"`
	KnownOutcomeJobs  interface{} `json:"known_outcome_jobs"`
	QueueTimedJobs    interface{} `json:"queue_timed_jobs"`
	AvgQueueSeconds   interface{} `json:"avg_queue_seconds"`
	AvgRuntimeSeconds interface{} `json:"avg_runtime_seconds"`
}

func (q *Queries) GetJobStatsSince(ctx context.Context, createdAt time.Time) (GetJobStatsSinceRow, error) {
	row := q.db.QueryRowContext(ctx, getJobStatsSince, createdAt)
	var i GetJobStatsSinceRow
	err := row.Scan(
		&i.TotalJobs,
		&i.SuccessfulJobs,
		&i.FailedJobs,
		&i.KnownOutcomeJobs,
		&i.QueueTimedJobs,
		&i.AvgQueueSeconds,
		&i.AvgRuntimeSeconds,
	)
	return i, err
}

const getOpenJobRow = `-- name: GetOpenJobRow :one
SELECT id FROM job_history
WHERE pool_id = ? AND runner_name = ? AND completed_at IS NULL
LIMIT 1
`

type GetOpenJobRowParams struct {
	PoolID     int64  `json:"pool_id"`
	RunnerName string `json:"runner_name"`
}

func (q *Queries) GetOpenJobRow(ctx context.Context, arg GetOpenJobRowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOpenJobRow, arg.PoolID, arg.RunnerName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listJobHistory = `-- name: ListJobHistory :many
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at FROM job_history
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListJobHistoryParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListJobHistory(ctx context.Context, arg ListJobHistoryParams) ([]JobHistory, error) {
	rows, err := q.db.QueryContext(ctx, listJobHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobHistory{}
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.RunnerName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LogRetentionPath,
			&i.JobID,
			&i.RunID,
			&i.WorkflowName,
			&i.HeadBranch,
			&i.HeadSha,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobHistoryByPoolId = `-- name: ListJobHistoryByPoolId :many
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at FROM job_history
WHERE pool_id = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListJobHistoryByPoolIdParams struct {
	PoolID int64 `json:"pool_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListJobHistoryByPoolId(ctx context.Context, arg ListJobHistoryByPoolIdParams) ([]JobHistory, error) {
	rows, err := q.db.QueryContext(ctx, listJobHistoryByPoolId, arg.PoolID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobHistory{}
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.RunnerName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LogRetentionPath,
			&i.JobID,
			&i.RunID,
			&i.WorkflowName,
			&i.HeadBranch,
			&i.HeadSha,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openJobLifecycleRow = `-- name: OpenJobLifecycleRow :one
INSERT INTO job_history (
    pool_id,
    runner_name,
    status,
    started_at,
    source
) VALUES (
    ?, ?, 'running', ?, 'transition'
) RETURNING id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at
`

type OpenJobLifecycleRowParams struct {
	PoolID     int64        `json:"pool_id"`
	RunnerName string       `json:"runner_name"`
	StartedAt  sql.NullTime `json:"started_at"`
}

func (q *Queries) OpenJobLifecycleRow(ctx context.Context, arg OpenJobLifecycleRowParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, openJobLifecycleRow, arg.PoolID, arg.RunnerName, arg.StartedAt)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.JobID,
		&i.RunID,
		&i.WorkflowName,
		&i.HeadBranch,
		&i.HeadSha,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const pruneJobHistoryOlderThan = `-- name: PruneJobHistoryOlderThan :many
DELETE FROM job_history
WHERE (completed_at IS NOT NULL AND completed_at < ?)
   OR (completed_at IS NULL AND created_at < ?)
RETURNING id, log_retention_path
`

type PruneJobHistoryOlderThanParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

type PruneJobHistoryOlderThanRow struct {
	ID               int64          `json:"id"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
}

func (q *Queries) PruneJobHistoryOlderThan(ctx context.Context, arg PruneJobHistoryOlderThanParams) ([]PruneJobHistoryOlderThanRow, error) {
	rows, err := q.db.QueryContext(ctx, pruneJobHistoryOlderThan, arg.CompletedAt, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PruneJobHistoryOlderThanRow{}
	for rows.Next() {
		var i PruneJobHistoryOlderThanRow
		if err := rows.Scan(&i.ID, &i.LogRetentionPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJobHistory = `-- name: SearchJobHistory :many
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at FROM job_history
WHERE (?1 = 0 OR pool_id = ?1)
  AND (?2 = '' OR runner_name LIKE '%' || ?2 || '%')
  AND (?3 = '' OR status = ?3)
ORDER BY id DESC
LIMIT ?5 OFFSET ?4
`

type SearchJobHistoryParams struct {
	PoolID interface{} `json:"pool_id"`
	Search interface{} `json:"search"`
	Status interface{} `json:"status"`
	Offset int64       `json:"offset"`
	Limit  int64       `json:"limit"`
}

func (q *Queries) SearchJobHistory(ctx context.Context, arg SearchJobHistoryParams) ([]JobHistory, error) {
	rows, err := q.db.QueryContext(ctx, searchJobHistory,
		arg.PoolID,
		arg.Search,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobHistory{}
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.RunnerName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LogRetentionPath,
			&i.JobID,
			&i.RunID,
			&i.WorkflowName,
			&i.HeadBranch,
			&i.HeadSha,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobHistoryStatus = `-- name: UpdateJobHistoryStatus :one
UPDATE job_history
SET status = ?,
    completed_at = ?,
    log_retention_path = ?
WHERE id = ?
RETURNING id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at
`

type UpdateJobHistoryStatusParams struct {
	Status           string         `json:"status"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateJobHistoryStatus(ctx context.Context, arg UpdateJobHistoryStatusParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, updateJobHistoryStatus,
		arg.Status,
		arg.CompletedAt,
		arg.LogRetentionPath,
		arg.ID,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.JobID,
		&i.RunID,
		&i.WorkflowName,
		&i.HeadBranch,
		&i.HeadSha,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}
