// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_history.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const attachWebhookToTransition = `-- name: AttachWebhookToTransition :execrows
UPDATE job_history
SET job_id = ?,
    status = 'running',
    queued_at = COALESCE(queued_at, ?),
    started_at = COALESCE(started_at, ?),
    run_id = COALESCE(?, run_id),
    workflow_name = COALESCE(?, workflow_name),
    head_branch = COALESCE(?, head_branch),
    head_sha = COALESCE(?, head_sha)
WHERE pool_id = ? AND runner_name = ? AND completed_at IS NULL
`

type AttachWebhookToTransitionParams struct {
	JobID        sql.NullInt64  `json:"job_id"`
	QueuedAt     sql.NullTime   `json:"queued_at"`
	StartedAt    sql.NullTime   `json:"started_at"`
	RunID        sql.NullInt64  `json:"run_id"`
	WorkflowName sql.NullString `json:"workflow_name"`
	HeadBranch   sql.NullString `json:"head_branch"`
	HeadSha      sql.NullString `json:"head_sha"`
	PoolID       int64          `json:"pool_id"`
	RunnerName   string         `json:"runner_name"`
}

// Webhook 'in_progress' arriving after (or before) the busy-sync transition
// row: attach the external identity and timestamps to the runner's open row
// (docs/21 section 5.5 merge rule 3). queued_at is adopted from the forge event -
// real data, never fabricated.
func (q *Queries) AttachWebhookToTransition(ctx context.Context, arg AttachWebhookToTransitionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, attachWebhookToTransition,
		arg.JobID,
		arg.QueuedAt,
		arg.StartedAt,
		arg.RunID,
		arg.WorkflowName,
		arg.HeadBranch,
		arg.HeadSha,
		arg.PoolID,
		arg.RunnerName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeAllOpenJobsInterrupted = `-- name: CloseAllOpenJobsInterrupted :execrows
UPDATE job_history
SET completed_at = ?,
    status = 'interrupted'
WHERE completed_at IS NULL
`

func (q *Queries) CloseAllOpenJobsInterrupted(ctx context.Context, completedAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeAllOpenJobsInterrupted, completedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeOpenJobRow = `-- name: CloseOpenJobRow :execrows
UPDATE job_history
SET completed_at = ?,
    status = ?,
    log_retention_path = ?,
    job_id = COALESCE(?, job_id)
WHERE pool_id = ?
  AND runner_name = ?
  AND completed_at IS NULL
`

type CloseOpenJobRowParams struct {
	CompletedAt      sql.NullTime   `json:"completed_at"`
	Status           string         `json:"status"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
	JobID            sql.NullInt64  `json:"job_id"`
	PoolID           int64          `json:"pool_id"`
	RunnerName       string         `json:"runner_name"`
}

func (q *Queries) CloseOpenJobRow(ctx context.Context, arg CloseOpenJobRowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeOpenJobRow,
		arg.CompletedAt,
		arg.Status,
		arg.LogRetentionPath,
		arg.JobID,
		arg.PoolID,
		arg.RunnerName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeOpenRowByRunnerEnrichJobID = `-- name: CloseOpenRowByRunnerEnrichJobID :execrows
UPDATE job_history
SET completed_at = ?,
    status = ?,
    job_id = ?
WHERE pool_id = ? AND runner_name = ? AND completed_at IS NULL
  AND (job_id IS NULL OR job_id = 0)
`

type CloseOpenRowByRunnerEnrichJobIDParams struct {
	CompletedAt sql.NullTime  `json:"completed_at"`
	Status      string        `json:"status"`
	JobID       sql.NullInt64 `json:"job_id"`
	PoolID      int64         `json:"pool_id"`
	RunnerName  string        `json:"runner_name"`
}

// Webhook 'completed' fallback: no row carries the external id (poll-opened
// transition row only) - close it and enrich it with the job id (docs/21 section 5.5).
func (q *Queries) CloseOpenRowByRunnerEnrichJobID(ctx context.Context, arg CloseOpenRowByRunnerEnrichJobIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeOpenRowByRunnerEnrichJobID,
		arg.CompletedAt,
		arg.Status,
		arg.JobID,
		arg.PoolID,
		arg.RunnerName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeOpenWebhookJobByID = `-- name: CloseOpenWebhookJobByID :execrows
UPDATE job_history
SET completed_at = ?,
    status = ?,
    runner_name = CASE WHEN COALESCE(runner_name, '') = '' THEN ? ELSE runner_name END
WHERE job_id = ? AND completed_at IS NULL
`

type CloseOpenWebhookJobByIDParams struct {
	CompletedAt sql.NullTime  `json:"completed_at"`
	Status      string        `json:"status"`
	RunnerName  string        `json:"runner_name"`
	JobID       sql.NullInt64 `json:"job_id"`
}

// Webhook 'completed' close keyed by the external job id; adopts the runner
// name when the closed row predates assignment (docs/21 section 5.5).
func (q *Queries) CloseOpenWebhookJobByID(ctx context.Context, arg CloseOpenWebhookJobByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeOpenWebhookJobByID,
		arg.CompletedAt,
		arg.Status,
		arg.RunnerName,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeStaleOpenJobsSince = `-- name: CloseStaleOpenJobsSince :execrows
UPDATE job_history
SET completed_at = ?,
    status = 'interrupted'
WHERE completed_at IS NULL
  AND started_at IS NOT NULL
  AND started_at < ?
  AND pool_id = ?
`

type CloseStaleOpenJobsSinceParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	StartedAt   sql.NullTime `json:"started_at"`
	PoolID      int64        `json:"pool_id"`
}

func (q *Queries) CloseStaleOpenJobsSince(ctx context.Context, arg CloseStaleOpenJobsSinceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeStaleOpenJobsSince, arg.CompletedAt, arg.StartedAt, arg.PoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countJobHistory = `-- name: CountJobHistory :one
SELECT COUNT(*) FROM job_history
`

func (q *Queries) CountJobHistory(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobHistory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobHistoryByPoolId = `-- name: CountJobHistoryByPoolId :one
SELECT COUNT(*) FROM job_history
WHERE pool_id = ?
`

func (q *Queries) CountJobHistoryByPoolId(ctx context.Context, poolID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobHistoryByPoolId, poolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchJobHistory = `-- name: CountSearchJobHistory :one
SELECT COUNT(*) FROM job_history
WHERE (?1 = 0 OR pool_id = ?1)
  AND (?2 = '' OR runner_name LIKE '%' || ?2 || '%')
  AND (?3 = '' OR status = ?3)
`

type CountSearchJobHistoryParams struct {
	PoolID interface{} `json:"pool_id"`
	Search interface{} `json:"search"`
	Status interface{} `json:"status"`
}

func (q *Queries) CountSearchJobHistory(ctx context.Context, arg CountSearchJobHistoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchJobHistory, arg.PoolID, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJobHistory = `-- name: CreateJobHistory :one
INSERT INTO job_history (
    pool_id,
    runner_name,
    status,
    queued_at,
    started_at,
    completed_at,
    log_retention_path,
    source
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at
`

type CreateJobHistoryParams struct {
	PoolID           int64          `json:"pool_id"`
	RunnerName       string         `json:"runner_name"`
	Status           string         `json:"status"`
	QueuedAt         sql.NullTime   `json:"queued_at"`
	StartedAt        sql.NullTime   `json:"started_at"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
	Source           string         `json:"source"`
}

func (q *Queries) CreateJobHistory(ctx context.Context, arg CreateJobHistoryParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, createJobHistory,
		arg.PoolID,
		arg.RunnerName,
		arg.Status,
		arg.QueuedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.LogRetentionPath,
		arg.Source,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.JobID,
		&i.RunID,
		&i.WorkflowName,
		&i.HeadBranch,
		&i.HeadSha,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJobHistoryOlderThan = `-- name: DeleteJobHistoryOlderThan :exec
DELETE FROM job_history
WHERE completed_at < ?
`

func (q *Queries) DeleteJobHistoryOlderThan(ctx context.Context, completedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteJobHistoryOlderThan, completedAt)
	return err
}

const deleteJobRowByID = `-- name: DeleteJobRowByID :exec
DELETE FROM job_history
WHERE id = ?
`

func (q *Queries) DeleteJobRowByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJobRowByID, id)
	return err
}

const deleteOpenTransitionRowsByRunner = `-- name: DeleteOpenTransitionRowsByRunner :execrows
DELETE FROM job_history
WHERE pool_id = ? AND runner_name = ? AND completed_at IS NULL
  AND (job_id IS NULL OR job_id = 0)
`

type DeleteOpenTransitionRowsByRunnerParams struct {
	PoolID     int64  `json:"pool_id"`
	RunnerName string `json:"runner_name"`
}

// Duplicate cleanup after closing by external job id: a poll-opened transition
// row (empty job id) for the same runner would double-count the job.
func (q *Queries) DeleteOpenTransitionRowsByRunner(ctx context.Context, arg DeleteOpenTransitionRowsByRunnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOpenTransitionRowsByRunner, arg.PoolID, arg.RunnerName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getHourlyJobStatsSince = `-- name: GetHourlyJobStatsSince :many
SELECT
    strftime('%Y-%m-%dT%H:00:00Z', created_at) as bucket_hour,
    COUNT(*) as total_jobs,
    COALESCE(SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END), 0) as successful_jobs,
    COALESCE(SUM(CASE WHEN status = 'failure' OR status = 'failed' THEN 1 ELSE 0 END), 0) as failed_jobs,
    COALESCE(SUM(CASE WHEN status IN ('success', 'failure', 'cancelled', 'timeout') THEN 1 ELSE 0 END), 0) as known_outcome_jobs,
    COALESCE(SUM(CASE WHEN queued_at IS NOT NULL THEN 1 ELSE 0 END), 0) as queue_timed_jobs,
    COALESCE(AVG(CASE WHEN started_at IS NOT NULL AND queued_at IS NOT NULL THEN (CAST(strftime('%s', replace(substr(started_at, 1, 19), 'T', ' ')) AS REAL) - CAST(strftime('%s', replace(substr(queued_at, 1, 19), 'T', ' ')) AS REAL)) END), 0.0) as avg_queue_seconds,
    COALESCE(AVG(CASE WHEN completed_at IS NOT NULL AND started_at IS NOT NULL THEN (CAST(strftime('%s', replace(substr(completed_at, 1, 19), 'T', ' ')) AS REAL) - CAST(strftime('%s', replace(substr(started_at, 1, 19), 'T', ' ')) AS REAL)) END), 0.0) as avg_runtime_seconds
FROM job_history
WHERE created_at >= ?
GROUP BY bucket_hour
ORDER BY bucket_hour ASC
`

type GetHourlyJobStatsSinceRow struct {
	BucketHour        interface{} `json:"bucket_hour"`
	TotalJobs         int64       `json:"total_jobs"`
	SuccessfulJobs    interface{} `json:"successful_jobs"`
	FailedJobs        interface{} `json:"failed_jobs"`
	KnownOutcomeJobs  interface{} `json:"known_outcome_jobs"`
	QueueTimedJobs    interface{} `json:"queue_timed_jobs"`
	AvgQueueSeconds   interface{} `json:"avg_queue_seconds"`
	AvgRuntimeSeconds interface{} `json:"avg_runtime_seconds"`
}

func (q *Queries) GetHourlyJobStatsSince(ctx context.Context, createdAt time.Time) ([]GetHourlyJobStatsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, getHourlyJobStatsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHourlyJobStatsSinceRow{}
	for rows.Next() {
		var i GetHourlyJobStatsSinceRow
		if err := rows.Scan(
			&i.BucketHour,
			&i.TotalJobs,
			&i.SuccessfulJobs,
			&i.FailedJobs,
			&i.KnownOutcomeJobs,
			&i.QueueTimedJobs,
			&i.AvgQueueSeconds,
			&i.AvgRuntimeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobHistoryById = `-- name: GetJobHistoryById :one
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at FROM job_history
WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobHistoryById(ctx context.Context, id int64) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, getJobHistoryById, id)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.JobID,
		&i.RunID,
		&i.WorkflowName,
		&i.HeadBranch,
		&i.HeadSha,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getJobStatsSince = `-- name: GetJobStatsSince :one
SELECT
    COUNT(*) as total_jobs,
    COALESCE(SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END), 0) as successful_jobs,
    COALESCE(SUM(CASE WHEN status = 'failure' OR status = 'failed' THEN 1 ELSE 0 END), 0) as failed_jobs,
    COALESCE(SUM(CASE WHEN status IN ('success', 'failure', 'cancelled', 'timeout') THEN 1 ELSE 0 END), 0) as known_outcome_jobs,
    COALESCE(SUM(CASE WHEN queued_at IS NOT NULL THEN 1 ELSE 0 END), 0) as queue_timed_jobs,
    COALESCE(AVG(CASE WHEN started_at IS NOT NULL AND queued_at IS NOT NULL THEN (CAST(strftime('%s', replace(substr(started_at, 1, 19), 'T', ' ')) AS REAL) - CAST(strftime('%s', replace(substr(queued_at, 1, 19), 'T', ' ')) AS REAL)) END), 0.0) as avg_queue_seconds,
    COALESCE(AVG(CASE WHEN completed_at IS NOT NULL AND started_at IS NOT NULL THEN (CAST(strftime('%s', replace(substr(completed_at, 1, 19), 'T', ' ')) AS REAL) - CAST(strftime('%s', replace(substr(started_at, 1, 19), 'T', ' ')) AS REAL)) END), 0.0) as avg_runtime_seconds
FROM job_history
WHERE created_at >= ?
`

type GetJobStatsSinceRow struct {
	TotalJobs         int64       `json:"total_jobs"`
	SuccessfulJobs    interface{} `json:"successful_jobs"`
	FailedJobs        interface{} `json:"failed_jobs"`
	KnownOutcomeJobs  interface{} `json:"known_outcome_jobs"`
	QueueTimedJobs    interface{} `json:"queue_timed_jobs"`
	AvgQueueSeconds   interface{} `json:"avg_queue_seconds"`
	AvgRuntimeSeconds interface{} `json:"avg_runtime_seconds"`
}

func (q *Queries) GetJobStatsSince(ctx context.Context, createdAt time.Time) (GetJobStatsSinceRow, error) {
	row := q.db.QueryRowContext(ctx, getJobStatsSince, createdAt)
	var i GetJobStatsSinceRow
	err := row.Scan(
		&i.TotalJobs,
		&i.SuccessfulJobs,
		&i.FailedJobs,
		&i.KnownOutcomeJobs,
		&i.QueueTimedJobs,
		&i.AvgQueueSeconds,
		&i.AvgRuntimeSeconds,
	)
	return i, err
}

const getOpenJobRow = `-- name: GetOpenJobRow :one
SELECT id FROM job_history
WHERE pool_id = ? AND runner_name = ? AND completed_at IS NULL
LIMIT 1
`

type GetOpenJobRowParams struct {
	PoolID     int64  `json:"pool_id"`
	RunnerName string `json:"runner_name"`
}

func (q *Queries) GetOpenJobRow(ctx context.Context, arg GetOpenJobRowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOpenJobRow, arg.PoolID, arg.RunnerName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOpenWebhookJobByID = `-- name: GetOpenWebhookJobByID :one
SELECT id, runner_name, queued_at FROM job_history
WHERE job_id = ? AND completed_at IS NULL
LIMIT 1
`

type GetOpenWebhookJobByIDRow struct {
	ID         int64        `json:"id"`
	RunnerName string       `json:"runner_name"`
	QueuedAt   sql.NullTime `json:"queued_at"`
}

func (q *Queries) GetOpenWebhookJobByID(ctx context.Context, jobID sql.NullInt64) (GetOpenWebhookJobByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOpenWebhookJobByID, jobID)
	var i GetOpenWebhookJobByIDRow
	err := row.Scan(&i.ID, &i.RunnerName, &i.QueuedAt)
	return i, err
}

const insertWebhookRunningJob = `-- name: InsertWebhookRunningJob :exec
INSERT INTO job_history (
    pool_id,
    runner_name,
    job_id,
    run_id,
    workflow_name,
    head_branch,
    head_sha,
    status,
    started_at,
    queued_at,
    source
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, 'running', ?, ?, 'webhook'
)
`

type InsertWebhookRunningJobParams struct {
	PoolID       int64          `json:"pool_id"`
	RunnerName   string         `json:"runner_name"`
	JobID        sql.NullInt64  `json:"job_id"`
	RunID        sql.NullInt64  `json:"run_id"`
	WorkflowName sql.NullString `json:"workflow_name"`
	HeadBranch   sql.NullString `json:"head_branch"`
	HeadSha      sql.NullString `json:"head_sha"`
	StartedAt    sql.NullTime   `json:"started_at"`
	QueuedAt     sql.NullTime   `json:"queued_at"`
}

// Webhook 'in_progress' with no pre-existing row at all (docs/21 section 5.5 merge rule 4).
func (q *Queries) InsertWebhookRunningJob(ctx context.Context, arg InsertWebhookRunningJobParams) error {
	_, err := q.db.ExecContext(ctx, insertWebhookRunningJob,
		arg.PoolID,
		arg.RunnerName,
		arg.JobID,
		arg.RunID,
		arg.WorkflowName,
		arg.HeadBranch,
		arg.HeadSha,
		arg.StartedAt,
		arg.QueuedAt,
	)
	return err
}

const listJobHistory = `-- name: ListJobHistory :many
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at FROM job_history
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListJobHistoryParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListJobHistory(ctx context.Context, arg ListJobHistoryParams) ([]JobHistory, error) {
	rows, err := q.db.QueryContext(ctx, listJobHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobHistory{}
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.RunnerName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LogRetentionPath,
			&i.JobID,
			&i.RunID,
			&i.WorkflowName,
			&i.HeadBranch,
			&i.HeadSha,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobHistoryByPoolId = `-- name: ListJobHistoryByPoolId :many
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at FROM job_history
WHERE pool_id = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListJobHistoryByPoolIdParams struct {
	PoolID int64 `json:"pool_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListJobHistoryByPoolId(ctx context.Context, arg ListJobHistoryByPoolIdParams) ([]JobHistory, error) {
	rows, err := q.db.QueryContext(ctx, listJobHistoryByPoolId, arg.PoolID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobHistory{}
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.RunnerName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LogRetentionPath,
			&i.JobID,
			&i.RunID,
			&i.WorkflowName,
			&i.HeadBranch,
			&i.HeadSha,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openJobLifecycleRow = `-- name: OpenJobLifecycleRow :one
INSERT INTO job_history (
    pool_id,
    runner_name,
    status,
    started_at,
    source
) VALUES (
    ?, ?, 'running', ?, 'transition'
) RETURNING id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at
`

type OpenJobLifecycleRowParams struct {
	PoolID     int64        `json:"pool_id"`
	RunnerName string       `json:"runner_name"`
	StartedAt  sql.NullTime `json:"started_at"`
}

func (q *Queries) OpenJobLifecycleRow(ctx context.Context, arg OpenJobLifecycleRowParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, openJobLifecycleRow, arg.PoolID, arg.RunnerName, arg.StartedAt)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.JobID,
		&i.RunID,
		&i.WorkflowName,
		&i.HeadBranch,
		&i.HeadSha,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const promoteWebhookStubToRunning = `-- name: PromoteWebhookStubToRunning :execrows
UPDATE job_history
SET runner_name = ?,
    status = 'running',
    started_at = COALESCE(started_at, ?)
WHERE id = ? AND completed_at IS NULL
`

type PromoteWebhookStubToRunningParams struct {
	RunnerName string       `json:"runner_name"`
	StartedAt  sql.NullTime `json:"started_at"`
	ID         int64        `json:"id"`
}

// Webhook 'in_progress' with a queued stub but no transition row: promote the
// stub in place (docs/21 section 5.5 merge rule 2).
func (q *Queries) PromoteWebhookStubToRunning(ctx context.Context, arg PromoteWebhookStubToRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promoteWebhookStubToRunning, arg.RunnerName, arg.StartedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneJobHistoryOlderThan = `-- name: PruneJobHistoryOlderThan :many
DELETE FROM job_history
WHERE (completed_at IS NOT NULL AND completed_at < ?)
   OR (completed_at IS NULL AND created_at < ?)
RETURNING id, log_retention_path
`

type PruneJobHistoryOlderThanParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

type PruneJobHistoryOlderThanRow struct {
	ID               int64          `json:"id"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
}

func (q *Queries) PruneJobHistoryOlderThan(ctx context.Context, arg PruneJobHistoryOlderThanParams) ([]PruneJobHistoryOlderThanRow, error) {
	rows, err := q.db.QueryContext(ctx, pruneJobHistoryOlderThan, arg.CompletedAt, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PruneJobHistoryOlderThanRow{}
	for rows.Next() {
		var i PruneJobHistoryOlderThanRow
		if err := rows.Scan(&i.ID, &i.LogRetentionPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJobHistory = `-- name: SearchJobHistory :many
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at FROM job_history
WHERE (?1 = 0 OR pool_id = ?1)
  AND (?2 = '' OR runner_name LIKE '%' || ?2 || '%')
  AND (?3 = '' OR status = ?3)
ORDER BY id DESC
LIMIT ?5 OFFSET ?4
`

type SearchJobHistoryParams struct {
	PoolID interface{} `json:"pool_id"`
	Search interface{} `json:"search"`
	Status interface{} `json:"status"`
	Offset int64       `json:"offset"`
	Limit  int64       `json:"limit"`
}

func (q *Queries) SearchJobHistory(ctx context.Context, arg SearchJobHistoryParams) ([]JobHistory, error) {
	rows, err := q.db.QueryContext(ctx, searchJobHistory,
		arg.PoolID,
		arg.Search,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobHistory{}
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.RunnerName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LogRetentionPath,
			&i.JobID,
			&i.RunID,
			&i.WorkflowName,
			&i.HeadBranch,
			&i.HeadSha,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobHistoryStatus = `-- name: UpdateJobHistoryStatus :one
UPDATE job_history
SET status = ?,
    completed_at = ?,
    log_retention_path = ?
WHERE id = ?
RETURNING id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, job_id, run_id, workflow_name, head_branch, head_sha, source, created_at
`

type UpdateJobHistoryStatusParams struct {
	Status           string         `json:"status"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateJobHistoryStatus(ctx context.Context, arg UpdateJobHistoryStatusParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, updateJobHistoryStatus,
		arg.Status,
		arg.CompletedAt,
		arg.LogRetentionPath,
		arg.ID,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.JobID,
		&i.RunID,
		&i.WorkflowName,
		&i.HeadBranch,
		&i.HeadSha,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const upgradeClosedJobRowConclusion = `-- name: UpgradeClosedJobRowConclusion :execrows
UPDATE job_history
SET completed_at = ?,
    status = ?
WHERE completed_at IS NOT NULL AND status = ? AND job_id = ?
`

type UpgradeClosedJobRowConclusionParams struct {
	CompletedAt sql.NullTime  `json:"completed_at"`
	Status      string        `json:"status"`
	Status_2    string        `json:"status_2"`
	JobID       sql.NullInt64 `json:"job_id"`
}

// Webhook completed event arriving after the death path already closed the
// row: an ephemeral runner exits before the forge event lands, so the row
// was closed as completed (exit 0, conclusion unknowable). The webhook
// conclusion is authoritative, so upgrade the closed row (docs/21 section 5.5).
// Rows closed as interrupted or timeout stay: the runner died or was killed
// mid-job, so any forge conclusion describes a requeued job, not this row.
func (q *Queries) UpgradeClosedJobRowConclusion(ctx context.Context, arg UpgradeClosedJobRowConclusionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upgradeClosedJobRowConclusion,
		arg.CompletedAt,
		arg.Status,
		arg.Status_2,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upgradeLatestNullJobRowConclusion = `-- name: UpgradeLatestNullJobRowConclusion :execrows
UPDATE job_history
SET status = ?,
    completed_at = ?,
    job_id = ?
WHERE id = (
    SELECT j.id FROM job_history j
    WHERE j.pool_id = ? AND j.runner_name = ? AND j.status = 'completed'
      AND j.completed_at IS NOT NULL AND (j.job_id IS NULL OR j.job_id = 0)
    ORDER BY j.completed_at DESC LIMIT 1
)
`

type UpgradeLatestNullJobRowConclusionParams struct {
	Status      string        `json:"status"`
	CompletedAt sql.NullTime  `json:"completed_at"`
	JobID       sql.NullInt64 `json:"job_id"`
	PoolID      int64         `json:"pool_id"`
	RunnerName  string        `json:"runner_name"`
}

// Same death-before-webhook race, poll-path variant: the transition row
// closed without an external job id, so the by-id upgrade above cannot
// match it. The completed event names the runner, so upgrade its newest
// closed completed row and stamp the job id onto it.
func (q *Queries) UpgradeLatestNullJobRowConclusion(ctx context.Context, arg UpgradeLatestNullJobRowConclusionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upgradeLatestNullJobRowConclusion,
		arg.Status,
		arg.CompletedAt,
		arg.JobID,
		arg.PoolID,
		arg.RunnerName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertWebhookQueuedJob = `-- name: UpsertWebhookQueuedJob :one
INSERT INTO job_history (
    pool_id,
    job_id,
    run_id,
    workflow_name,
    head_branch,
    head_sha,
    status,
    queued_at,
    source,
    runner_name
) VALUES (
    ?, ?, ?, ?, ?, ?, 'queued', ?, 'webhook', ''
)
ON CONFLICT(job_id) DO UPDATE SET
    queued_at = COALESCE(job_history.queued_at, excluded.queued_at),
    run_id = COALESCE(excluded.run_id, job_history.run_id),
    workflow_name = COALESCE(excluded.workflow_name, job_history.workflow_name),
    head_branch = COALESCE(excluded.head_branch, job_history.head_branch),
    head_sha = COALESCE(excluded.head_sha, job_history.head_sha)
WHERE job_history.completed_at IS NULL
RETURNING id
`

type UpsertWebhookQueuedJobParams struct {
	PoolID       int64          `json:"pool_id"`
	JobID        sql.NullInt64  `json:"job_id"`
	RunID        sql.NullInt64  `json:"run_id"`
	WorkflowName sql.NullString `json:"workflow_name"`
	HeadBranch   sql.NullString `json:"head_branch"`
	HeadSha      sql.NullString `json:"head_sha"`
	QueuedAt     sql.NullTime   `json:"queued_at"`
}

// Webhook 'queued' upsert keyed by the external job id (docs/21 section 5.5).
// Conflicts only fill in missing metadata: status, runner assignment, and the
// original queued_at are never rewritten by a (re)delivery.
func (q *Queries) UpsertWebhookQueuedJob(ctx context.Context, arg UpsertWebhookQueuedJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertWebhookQueuedJob,
		arg.PoolID,
		arg.JobID,
		arg.RunID,
		arg.WorkflowName,
		arg.HeadBranch,
		arg.HeadSha,
		arg.QueuedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
