// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_rate_failures.sql

package db

import (
	"context"
	"time"
)

const deleteLoginRateFailuresBefore = `-- name: DeleteLoginRateFailuresBefore :exec
DELETE FROM login_rate_failures WHERE failed_at <= ?
`

func (q *Queries) DeleteLoginRateFailuresBefore(ctx context.Context, failedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteLoginRateFailuresBefore, failedAt)
	return err
}

const deleteLoginRateFailuresByKey = `-- name: DeleteLoginRateFailuresByKey :exec
DELETE FROM login_rate_failures WHERE rate_key = ?
`

func (q *Queries) DeleteLoginRateFailuresByKey(ctx context.Context, rateKey string) error {
	_, err := q.db.ExecContext(ctx, deleteLoginRateFailuresByKey, rateKey)
	return err
}

const insertLoginRateFailure = `-- name: InsertLoginRateFailure :exec

INSERT INTO login_rate_failures (rate_key, failed_at)
VALUES (?, ?)
`

type InsertLoginRateFailureParams struct {
	RateKey  string    `json:"rate_key"`
	FailedAt time.Time `json:"failed_at"`
}

// Durable login rate limiter state (RUN-238, docs/32 section 4.2): one row
// per failed login attempt, keyed by username+IP (rateLimitKey). The limiter
// writes through on every failure, deletes a key's rows on successful login,
// and reloads in-window rows on boot so a restart cannot reset a lockout.
func (q *Queries) InsertLoginRateFailure(ctx context.Context, arg InsertLoginRateFailureParams) error {
	_, err := q.db.ExecContext(ctx, insertLoginRateFailure, arg.RateKey, arg.FailedAt)
	return err
}

const listLoginRateFailuresSince = `-- name: ListLoginRateFailuresSince :many
SELECT rate_key, failed_at FROM login_rate_failures WHERE failed_at > ?
`

type ListLoginRateFailuresSinceRow struct {
	RateKey  string    `json:"rate_key"`
	FailedAt time.Time `json:"failed_at"`
}

func (q *Queries) ListLoginRateFailuresSince(ctx context.Context, failedAt time.Time) ([]ListLoginRateFailuresSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoginRateFailuresSince, failedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoginRateFailuresSinceRow{}
	for rows.Next() {
		var i ListLoginRateFailuresSinceRow
		if err := rows.Scan(&i.RateKey, &i.FailedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
