// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AdminUser struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type AppSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AuditLog struct {
	ID           int64          `json:"id"`
	UserID       sql.NullInt64  `json:"user_id"`
	Action       string         `json:"action"`
	ResourceType sql.NullString `json:"resource_type"`
	ResourceID   sql.NullInt64  `json:"resource_id"`
	Details      sql.NullString `json:"details"`
	CreatedAt    time.Time      `json:"created_at"`
}

type AuthProfile struct {
	ID                  int64          `json:"id"`
	Name                string         `json:"name"`
	AuthMethod          string         `json:"auth_method"`
	AppID               sql.NullInt64  `json:"app_id"`
	PrivateKeyEncrypted sql.NullString `json:"private_key_encrypted"`
	TokenEncrypted      sql.NullString `json:"token_encrypted"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type JobHistory struct {
	ID               int64          `json:"id"`
	PoolID           int64          `json:"pool_id"`
	RunnerName       string         `json:"runner_name"`
	Status           string         `json:"status"`
	QueuedAt         sql.NullTime   `json:"queued_at"`
	StartedAt        sql.NullTime   `json:"started_at"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
	JobID            sql.NullInt64  `json:"job_id"`
	RunID            sql.NullInt64  `json:"run_id"`
	WorkflowName     sql.NullString `json:"workflow_name"`
	HeadBranch       sql.NullString `json:"head_branch"`
	HeadSha          sql.NullString `json:"head_sha"`
	Source           string         `json:"source"`
	CreatedAt        time.Time      `json:"created_at"`
}

type PoolTarget struct {
	ID        int64     `json:"id"`
	PoolID    int64     `json:"pool_id"`
	TargetUrl string    `json:"target_url"`
	CreatedAt time.Time `json:"created_at"`
}

type RenovateConfig struct {
	ID           int64          `json:"id"`
	PoolID       int64          `json:"pool_id"`
	Enabled      bool           `json:"enabled"`
	CronSchedule sql.NullString `json:"cron_schedule"`
	Image        string         `json:"image"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type RenovateRun struct {
	ID          int64          `json:"id"`
	PoolID      int64          `json:"pool_id"`
	Status      string         `json:"status"`
	StartedAt   time.Time      `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	Summary     string         `json:"summary"`
	ContainerID sql.NullString `json:"container_id"`
	CreatedAt   time.Time      `json:"created_at"`
}

type RunnerPool struct {
	ID                       int64          `json:"id"`
	Name                     string         `json:"name"`
	Provider                 string         `json:"provider"`
	RepositoryUrl            string         `json:"repository_url"`
	Scope                    string         `json:"scope"`
	AuthProfileID            int64          `json:"auth_profile_id"`
	MinIdleRunners           int64          `json:"min_idle_runners"`
	MaxConcurrency           int64          `json:"max_concurrency"`
	Labels                   string         `json:"labels"`
	RunnerImage              string         `json:"runner_image"`
	AllowDocker              bool           `json:"allow_docker"`
	MaxRunnerLifetimeSeconds int64          `json:"max_runner_lifetime_seconds"`
	CpuLimit                 sql.NullString `json:"cpu_limit"`
	MemoryLimit              sql.NullString `json:"memory_limit"`
	CreatedAt                time.Time      `json:"created_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
	PollFallback             bool           `json:"poll_fallback"`
	PollIntervalSeconds      int64          `json:"poll_interval_seconds"`
}

type Session struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}
