// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pool_targets.sql

package db

import (
	"context"
)

const addPoolTarget = `-- name: AddPoolTarget :one
INSERT INTO pool_targets (
    pool_id,
    target_url
) VALUES (
    ?, ?
) RETURNING id, pool_id, target_url, created_at
`

type AddPoolTargetParams struct {
	PoolID    int64  `json:"pool_id"`
	TargetUrl string `json:"target_url"`
}

func (q *Queries) AddPoolTarget(ctx context.Context, arg AddPoolTargetParams) (PoolTarget, error) {
	row := q.db.QueryRowContext(ctx, addPoolTarget, arg.PoolID, arg.TargetUrl)
	var i PoolTarget
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.TargetUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deletePoolTarget = `-- name: DeletePoolTarget :exec
DELETE FROM pool_targets
WHERE pool_id = ? AND target_url = ?
`

type DeletePoolTargetParams struct {
	PoolID    int64  `json:"pool_id"`
	TargetUrl string `json:"target_url"`
}

func (q *Queries) DeletePoolTarget(ctx context.Context, arg DeletePoolTargetParams) error {
	_, err := q.db.ExecContext(ctx, deletePoolTarget, arg.PoolID, arg.TargetUrl)
	return err
}

const deletePoolTargetsByPoolId = `-- name: DeletePoolTargetsByPoolId :exec
DELETE FROM pool_targets
WHERE pool_id = ?
`

func (q *Queries) DeletePoolTargetsByPoolId(ctx context.Context, poolID int64) error {
	_, err := q.db.ExecContext(ctx, deletePoolTargetsByPoolId, poolID)
	return err
}

const getPoolByTargetUrl = `-- name: GetPoolByTargetUrl :one
SELECT rp.id, rp.name, rp.provider, rp.repository_url, rp.scope, rp.auth_profile_id, rp.min_idle_runners, rp.max_concurrency, rp.labels, rp.runner_image, rp.allow_docker, rp.max_runner_lifetime_seconds, rp.cpu_limit, rp.memory_limit, rp.created_at, rp.updated_at, rp.poll_fallback, rp.poll_interval_seconds FROM runner_pools rp
JOIN pool_targets pt ON rp.id = pt.pool_id
WHERE pt.target_url = ?
LIMIT 1
`

func (q *Queries) GetPoolByTargetUrl(ctx context.Context, targetUrl string) (RunnerPool, error) {
	row := q.db.QueryRowContext(ctx, getPoolByTargetUrl, targetUrl)
	var i RunnerPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.RepositoryUrl,
		&i.Scope,
		&i.AuthProfileID,
		&i.MinIdleRunners,
		&i.MaxConcurrency,
		&i.Labels,
		&i.RunnerImage,
		&i.AllowDocker,
		&i.MaxRunnerLifetimeSeconds,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PollFallback,
		&i.PollIntervalSeconds,
	)
	return i, err
}

const listAllPoolTargets = `-- name: ListAllPoolTargets :many
SELECT id, pool_id, target_url, created_at FROM pool_targets
ORDER BY pool_id ASC, target_url ASC
`

func (q *Queries) ListAllPoolTargets(ctx context.Context) ([]PoolTarget, error) {
	rows, err := q.db.QueryContext(ctx, listAllPoolTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolTarget{}
	for rows.Next() {
		var i PoolTarget
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.TargetUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolTargetsByPoolId = `-- name: ListPoolTargetsByPoolId :many
SELECT id, pool_id, target_url, created_at FROM pool_targets
WHERE pool_id = ?
ORDER BY target_url ASC
`

func (q *Queries) ListPoolTargetsByPoolId(ctx context.Context, poolID int64) ([]PoolTarget, error) {
	rows, err := q.db.QueryContext(ctx, listPoolTargetsByPoolId, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolTarget{}
	for rows.Next() {
		var i PoolTarget
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.TargetUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolsByTargetUrl = `-- name: ListPoolsByTargetUrl :many
SELECT rp.id, rp.name, rp.provider, rp.repository_url, rp.scope, rp.auth_profile_id, rp.min_idle_runners, rp.max_concurrency, rp.labels, rp.runner_image, rp.allow_docker, rp.max_runner_lifetime_seconds, rp.cpu_limit, rp.memory_limit, rp.created_at, rp.updated_at, rp.poll_fallback, rp.poll_interval_seconds FROM runner_pools rp
JOIN pool_targets pt ON rp.id = pt.pool_id
WHERE pt.target_url = ?
ORDER BY rp.name ASC
`

func (q *Queries) ListPoolsByTargetUrl(ctx context.Context, targetUrl string) ([]RunnerPool, error) {
	rows, err := q.db.QueryContext(ctx, listPoolsByTargetUrl, targetUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunnerPool{}
	for rows.Next() {
		var i RunnerPool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.RepositoryUrl,
			&i.Scope,
			&i.AuthProfileID,
			&i.MinIdleRunners,
			&i.MaxConcurrency,
			&i.Labels,
			&i.RunnerImage,
			&i.AllowDocker,
			&i.MaxRunnerLifetimeSeconds,
			&i.CpuLimit,
			&i.MemoryLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PollFallback,
			&i.PollIntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
