// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pool_tombstones.sql

package db

import (
	"context"
)

const insertPoolTombstone = `-- name: InsertPoolTombstone :exec

INSERT INTO pool_tombstones (pool_id, pool_name)
VALUES (?, ?)
ON CONFLICT(pool_id) DO UPDATE SET
    pool_name = excluded.pool_name,
    deleted_at = CURRENT_TIMESTAMP
`

type InsertPoolTombstoneParams struct {
	PoolID   int64  `json:"pool_id"`
	PoolName string `json:"pool_name"`
}

// Pool tombstones (RUN-239, docs/33 section 3.1): ownership evidence left
// behind by pool deletions. The reconcile removed-pool drain only proceeds
// for pool ids that carry a tombstone; ids without one belong to a foreign
// supervisor instance on a shared engine and are never touched.
// Idempotent: a pool id can only be deleted once (AUTOINCREMENT ids are
// never reused), but the upsert keeps the write safe under replay.
func (q *Queries) InsertPoolTombstone(ctx context.Context, arg InsertPoolTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, insertPoolTombstone, arg.PoolID, arg.PoolName)
	return err
}

const poolTombstoneExists = `-- name: PoolTombstoneExists :one
SELECT EXISTS (
    SELECT 1 FROM pool_tombstones WHERE pool_id = ?
) AS present
`

func (q *Queries) PoolTombstoneExists(ctx context.Context, poolID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, poolTombstoneExists, poolID)
	var present bool
	err := row.Scan(&present)
	return present, err
}
