// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddPoolTarget(ctx context.Context, arg AddPoolTargetParams) (PoolTarget, error)
	// Webhook 'in_progress' arriving after (or before) the busy-sync transition
	// row: attach the external identity and timestamps to the runner's open row
	// (docs/21 section 5.5 merge rule 3). queued_at is adopted from the forge event -
	// real data, never fabricated.
	AttachWebhookToTransition(ctx context.Context, arg AttachWebhookToTransitionParams) (int64, error)
	CloseAllOpenJobsInterrupted(ctx context.Context, completedAt sql.NullTime) (int64, error)
	CloseOpenJobRow(ctx context.Context, arg CloseOpenJobRowParams) (int64, error)
	// Webhook 'completed' fallback: no row carries the external id (poll-opened
	// transition row only) - close it and enrich it with the job id (docs/21 section 5.5).
	CloseOpenRowByRunnerEnrichJobID(ctx context.Context, arg CloseOpenRowByRunnerEnrichJobIDParams) (int64, error)
	// Webhook 'completed' close keyed by the external job id; adopts the runner
	// name when the closed row predates assignment (docs/21 section 5.5).
	CloseOpenWebhookJobByID(ctx context.Context, arg CloseOpenWebhookJobByIDParams) (int64, error)
	CloseStaleOpenJobsSince(ctx context.Context, arg CloseStaleOpenJobsSinceParams) (int64, error)
	CompleteRenovateRun(ctx context.Context, arg CompleteRenovateRunParams) (RenovateRun, error)
	CompleteRenovateRunByContainerID(ctx context.Context, arg CompleteRenovateRunByContainerIDParams) (RenovateRun, error)
	CountAdminRoleUsers(ctx context.Context) (int64, error)
	CountAdminUsers(ctx context.Context) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountAuthProfiles(ctx context.Context) (int64, error)
	CountJobHistory(ctx context.Context) (int64, error)
	CountJobHistoryByPoolId(ctx context.Context, poolID int64) (int64, error)
	CountRenovateRunsByPoolId(ctx context.Context, poolID int64) (int64, error)
	CountRunnerPools(ctx context.Context) (int64, error)
	CountSearchJobHistory(ctx context.Context, arg CountSearchJobHistoryParams) (int64, error)
	CountWebauthnCredentialsByUserId(ctx context.Context, userID int64) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateAuthProfile(ctx context.Context, arg CreateAuthProfileParams) (AuthProfile, error)
	CreateJobHistory(ctx context.Context, arg CreateJobHistoryParams) (JobHistory, error)
	CreateRenovateConfig(ctx context.Context, arg CreateRenovateConfigParams) (RenovateConfig, error)
	CreateRenovateRun(ctx context.Context, arg CreateRenovateRunParams) (RenovateRun, error)
	CreateRunnerPool(ctx context.Context, arg CreateRunnerPoolParams) (RunnerPool, error)
	// Every column is set explicitly: SQLite cannot ALTER a non-constant
	// DEFAULT onto a populated table (migration 009), so last_seen_at carries
	// a sentinel default that must never survive in data.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// WebAuthn credential storage (RUN-247, docs/34 sections 3.6 and 6). Rows
	// are public material only: COSE public keys, credential IDs, counters and
	// flags. The credential_id UNIQUE column is the passwordless-login identity
	// lookup (docs/34 section 3.2); ownership-scoped statements carry user_id so
	// a caller can only ever touch their own rows (docs/34 section 3.9).
	CreateWebauthnCredential(ctx context.Context, arg CreateWebauthnCredentialParams) (WebauthnCredential, error)
	DeleteAdminUser(ctx context.Context, id int64) error
	DeleteAppSetting(ctx context.Context, key string) error
	DeleteAuthProfile(ctx context.Context, id int64) error
	DeleteJobHistoryOlderThan(ctx context.Context, completedAt sql.NullTime) error
	DeleteJobRowByID(ctx context.Context, id int64) error
	DeleteLoginRateFailuresBefore(ctx context.Context, failedAt time.Time) error
	DeleteLoginRateFailuresByKey(ctx context.Context, rateKey string) error
	// Duplicate cleanup after closing by external job id: a poll-opened transition
	// row (empty job id) for the same runner would double-count the job.
	DeleteOpenTransitionRowsByRunner(ctx context.Context, arg DeleteOpenTransitionRowsByRunnerParams) (int64, error)
	// Revoke every session owned by the caller except the current row.
	DeleteOtherSessionsByUserId(ctx context.Context, arg DeleteOtherSessionsByUserIdParams) (int64, error)
	DeletePoolTarget(ctx context.Context, arg DeletePoolTargetParams) error
	DeletePoolTargetsByPoolId(ctx context.Context, poolID int64) error
	DeleteRenovateConfigByPoolId(ctx context.Context, poolID int64) error
	DeleteRenovateRunsByPoolId(ctx context.Context, poolID int64) error
	DeleteRunnerPool(ctx context.Context, id int64) error
	// Revoke one of the caller's sessions. The user_id guard is the query-level
	// ownership check (docs/32 section 3.5): a row owned by someone else never
	// matches, so foreign ids answer zero rows.
	DeleteSessionByIdAndUserId(ctx context.Context, arg DeleteSessionByIdAndUserIdParams) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteSessionsByUserId(ctx context.Context, userID int64) error
	DeleteWebauthnCredentialByIdAndUserId(ctx context.Context, arg DeleteWebauthnCredentialByIdAndUserIdParams) (int64, error)
	GetAdminUserById(ctx context.Context, id int64) (AdminUser, error)
	GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error)
	GetAppSetting(ctx context.Context, key string) (AppSetting, error)
	GetAuditLogById(ctx context.Context, id int64) (AuditLog, error)
	GetAuthProfileById(ctx context.Context, id int64) (AuthProfile, error)
	GetAuthProfileByName(ctx context.Context, name string) (AuthProfile, error)
	GetHourlyJobStatsSince(ctx context.Context, createdAt time.Time) ([]GetHourlyJobStatsSinceRow, error)
	GetJobHistoryById(ctx context.Context, id int64) (JobHistory, error)
	GetJobStatsSince(ctx context.Context, createdAt time.Time) (GetJobStatsSinceRow, error)
	// Resolves a runner's most recent historical log capture path by container
	// name (RUN-252): captures are filed on disk under the Docker container ID,
	// while the UI and job history key runners by name. Ordered newest-first so
	// reused names resolve to the latest capture; open rows (no completed_at,
	// no retention path) never match.
	GetLatestJobRetentionPathByRunnerName(ctx context.Context, runnerName string) (sql.NullString, error)
	GetLatestRenovateRunByPoolId(ctx context.Context, poolID int64) (RenovateRun, error)
	GetOpenJobRow(ctx context.Context, arg GetOpenJobRowParams) (int64, error)
	GetOpenWebhookJobByID(ctx context.Context, jobID sql.NullInt64) (GetOpenWebhookJobByIDRow, error)
	GetPoolByTargetUrl(ctx context.Context, targetUrl string) (RunnerPool, error)
	GetRenovateConfigByPoolId(ctx context.Context, poolID int64) (RenovateConfig, error)
	GetRenovateRun(ctx context.Context, id int64) (RenovateRun, error)
	GetRenovateRunByContainerID(ctx context.Context, containerID sql.NullString) (RenovateRun, error)
	GetRunnerPoolById(ctx context.Context, id int64) (RunnerPool, error)
	GetRunnerPoolByName(ctx context.Context, name string) (RunnerPool, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	// The passwordless-login identity lookup: raw credential ID to row (docs/34
	// section 3.2).
	GetWebauthnCredentialById(ctx context.Context, credentialID []byte) (WebauthnCredential, error)
	// Ownership-scoped single-row fetch for Rename/Delete pre-checks.
	GetWebauthnCredentialByIdAndUserId(ctx context.Context, arg GetWebauthnCredentialByIdAndUserIdParams) (WebauthnCredential, error)
	// Durable login rate limiter state (RUN-238, docs/32 section 4.2): one row
	// per failed login attempt, keyed by username+IP (rateLimitKey). The limiter
	// writes through on every failure, deletes a key's rows on successful login,
	// and reloads in-window rows on boot so a restart cannot reset a lockout.
	InsertLoginRateFailure(ctx context.Context, arg InsertLoginRateFailureParams) error
	// Pool tombstones (RUN-239, docs/33 section 3.1): ownership evidence left
	// behind by pool deletions. The reconcile removed-pool drain only proceeds
	// for pool ids that carry a tombstone; ids without one belong to a foreign
	// supervisor instance on a shared engine and are never touched.
	// Idempotent: a pool id can only be deleted once (AUTOINCREMENT ids are
	// never reused), but the upsert keeps the write safe under replay.
	InsertPoolTombstone(ctx context.Context, arg InsertPoolTombstoneParams) error
	// Webhook 'in_progress' with no pre-existing row at all (docs/21 section 5.5 merge rule 4).
	InsertWebhookRunningJob(ctx context.Context, arg InsertWebhookRunningJobParams) error
	ListAdminUsers(ctx context.Context) ([]AdminUser, error)
	ListAllPoolTargets(ctx context.Context) ([]PoolTarget, error)
	ListAppSettings(ctx context.Context) ([]AppSetting, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByUserId(ctx context.Context, arg ListAuditLogsByUserIdParams) ([]AuditLog, error)
	ListAuthProfiles(ctx context.Context) ([]AuthProfile, error)
	ListEnabledRenovateConfigs(ctx context.Context) ([]RenovateConfig, error)
	ListJobHistory(ctx context.Context, arg ListJobHistoryParams) ([]JobHistory, error)
	ListJobHistoryByPoolId(ctx context.Context, arg ListJobHistoryByPoolIdParams) ([]JobHistory, error)
	ListLoginRateFailuresSince(ctx context.Context, failedAt time.Time) ([]ListLoginRateFailuresSinceRow, error)
	ListPoolTargetsByPoolId(ctx context.Context, poolID int64) ([]PoolTarget, error)
	ListPoolsByTargetUrl(ctx context.Context, targetUrl string) ([]RunnerPool, error)
	ListRenovateConfigs(ctx context.Context) ([]RenovateConfig, error)
	ListRenovateRunsByPoolId(ctx context.Context, arg ListRenovateRunsByPoolIdParams) ([]RenovateRun, error)
	ListRunnerPools(ctx context.Context) ([]RunnerPool, error)
	ListSessionsByUserId(ctx context.Context, userID int64) ([]Session, error)
	ListWebauthnCredentialsByUserId(ctx context.Context, userID int64) ([]WebauthnCredential, error)
	OpenJobLifecycleRow(ctx context.Context, arg OpenJobLifecycleRowParams) (JobHistory, error)
	PoolTombstoneExists(ctx context.Context, poolID int64) (bool, error)
	// Webhook 'in_progress' with a queued stub but no transition row: promote the
	// stub in place (docs/21 section 5.5 merge rule 2).
	PromoteWebhookStubToRunning(ctx context.Context, arg PromoteWebhookStubToRunningParams) (int64, error)
	PruneJobHistoryOlderThan(ctx context.Context, arg PruneJobHistoryOlderThanParams) ([]PruneJobHistoryOlderThanRow, error)
	// Hourly maintenance (docs/32 section 5.2): enforce the audit retention
	// horizon (default 90d).
	PurgeAuditLogsOlderThan(ctx context.Context, createdAt time.Time) (int64, error)
	// Hourly maintenance (docs/32 section 5.2): delete sessions past either
	// clock - the sliding idle deadline or the fixed absolute cap.
	PurgeExpiredSessions(ctx context.Context, now time.Time) (int64, error)
	RenameWebauthnCredential(ctx context.Context, arg RenameWebauthnCredentialParams) (int64, error)
	SearchJobHistory(ctx context.Context, arg SearchJobHistoryParams) ([]JobHistory, error)
	SetAppSetting(ctx context.Context, arg SetAppSettingParams) (AppSetting, error)
	// Fail-closed flag on a non-increasing sign counter (docs/34 section 3.8):
	// a flagged credential refuses all further assertions until removed.
	SetWebauthnCredentialCloneWarning(ctx context.Context, credentialID []byte) error
	// Sliding renewal (docs/32 section 3.3): extend the idle deadline and record
	// the activity instant. Callers clamp expires_at at absolute_expires_at before
	// writing: the cap is never extended.
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) (AdminUser, error)
	UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) (AdminUser, error)
	UpdateAuthProfile(ctx context.Context, arg UpdateAuthProfileParams) (AuthProfile, error)
	UpdateJobHistoryStatus(ctx context.Context, arg UpdateJobHistoryStatusParams) (JobHistory, error)
	UpdateRenovateConfig(ctx context.Context, arg UpdateRenovateConfigParams) (RenovateConfig, error)
	UpdateRenovateRunContainerID(ctx context.Context, arg UpdateRenovateRunContainerIDParams) error
	UpdateRunnerPool(ctx context.Context, arg UpdateRunnerPoolParams) (RunnerPool, error)
	// Called after every successful assertion (docs/34 section 3.8): the
	// library's counter policy result plus the response's backup flags and the
	// last-use stamp.
	UpdateWebauthnCredentialAssertionState(ctx context.Context, arg UpdateWebauthnCredentialAssertionStateParams) error
	// Webhook completed event arriving after the death path already closed the
	// row: an ephemeral runner exits before the forge event lands, so the row
	// was closed as completed (exit 0, conclusion unknowable). The webhook
	// conclusion is authoritative, so upgrade the closed row (docs/21 section 5.5).
	// Rows closed as interrupted or timeout stay: the runner died or was killed
	// mid-job, so any forge conclusion describes a requeued job, not this row.
	UpgradeClosedJobRowConclusion(ctx context.Context, arg UpgradeClosedJobRowConclusionParams) (int64, error)
	// Same death-before-webhook race, poll-path variant: the transition row
	// closed without an external job id, so the by-id upgrade above cannot
	// match it. The completed event names the runner, so upgrade its newest
	// closed completed row and stamp the job id onto it.
	UpgradeLatestNullJobRowConclusion(ctx context.Context, arg UpgradeLatestNullJobRowConclusionParams) (int64, error)
	// Webhook 'queued' upsert keyed by the external job id (docs/21 section 5.5).
	// Conflicts only fill in missing metadata: status, runner assignment, and the
	// original queued_at are never rewritten by a (re)delivery.
	UpsertWebhookQueuedJob(ctx context.Context, arg UpsertWebhookQueuedJobParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
