// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddPoolTarget(ctx context.Context, arg AddPoolTargetParams) (PoolTarget, error)
	// Webhook 'in_progress' arriving after (or before) the busy-sync transition
	// row: attach the external identity and timestamps to the runner's open row
	// (docs/21 section 5.5 merge rule 3). queued_at is adopted from the forge event -
	// real data, never fabricated.
	AttachWebhookToTransition(ctx context.Context, arg AttachWebhookToTransitionParams) (int64, error)
	CloseAllOpenJobsInterrupted(ctx context.Context, completedAt sql.NullTime) (int64, error)
	CloseOpenJobRow(ctx context.Context, arg CloseOpenJobRowParams) (int64, error)
	// Webhook 'completed' fallback: no row carries the external id (poll-opened
	// transition row only) - close it and enrich it with the job id (docs/21 section 5.5).
	CloseOpenRowByRunnerEnrichJobID(ctx context.Context, arg CloseOpenRowByRunnerEnrichJobIDParams) (int64, error)
	// Webhook 'completed' close keyed by the external job id; adopts the runner
	// name when the closed row predates assignment (docs/21 section 5.5).
	CloseOpenWebhookJobByID(ctx context.Context, arg CloseOpenWebhookJobByIDParams) (int64, error)
	CloseStaleOpenJobsSince(ctx context.Context, arg CloseStaleOpenJobsSinceParams) (int64, error)
	CompleteRenovateRun(ctx context.Context, arg CompleteRenovateRunParams) (RenovateRun, error)
	CompleteRenovateRunByContainerID(ctx context.Context, arg CompleteRenovateRunByContainerIDParams) (RenovateRun, error)
	CountAdminUsers(ctx context.Context) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountAuthProfiles(ctx context.Context) (int64, error)
	CountJobHistory(ctx context.Context) (int64, error)
	CountJobHistoryByPoolId(ctx context.Context, poolID int64) (int64, error)
	CountRenovateRunsByPoolId(ctx context.Context, poolID int64) (int64, error)
	CountRunnerPools(ctx context.Context) (int64, error)
	CountSearchJobHistory(ctx context.Context, arg CountSearchJobHistoryParams) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateAuthProfile(ctx context.Context, arg CreateAuthProfileParams) (AuthProfile, error)
	CreateJobHistory(ctx context.Context, arg CreateJobHistoryParams) (JobHistory, error)
	CreateRenovateConfig(ctx context.Context, arg CreateRenovateConfigParams) (RenovateConfig, error)
	CreateRenovateRun(ctx context.Context, arg CreateRenovateRunParams) (RenovateRun, error)
	CreateRunnerPool(ctx context.Context, arg CreateRunnerPoolParams) (RunnerPool, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteAdminUser(ctx context.Context, id int64) error
	DeleteAppSetting(ctx context.Context, key string) error
	DeleteAuthProfile(ctx context.Context, id int64) error
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error
	DeleteJobHistoryOlderThan(ctx context.Context, completedAt sql.NullTime) error
	DeleteJobRowByID(ctx context.Context, id int64) error
	// Duplicate cleanup after closing by external job id: a poll-opened transition
	// row (empty job id) for the same runner would double-count the job.
	DeleteOpenTransitionRowsByRunner(ctx context.Context, arg DeleteOpenTransitionRowsByRunnerParams) (int64, error)
	DeletePoolTarget(ctx context.Context, arg DeletePoolTargetParams) error
	DeletePoolTargetsByPoolId(ctx context.Context, poolID int64) error
	DeleteRenovateConfigByPoolId(ctx context.Context, poolID int64) error
	DeleteRenovateRunsByPoolId(ctx context.Context, poolID int64) error
	DeleteRunnerPool(ctx context.Context, id int64) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteSessionsByUserId(ctx context.Context, userID int64) error
	GetAdminUserById(ctx context.Context, id int64) (AdminUser, error)
	GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error)
	GetAppSetting(ctx context.Context, key string) (AppSetting, error)
	GetAuditLogById(ctx context.Context, id int64) (AuditLog, error)
	GetAuthProfileById(ctx context.Context, id int64) (AuthProfile, error)
	GetAuthProfileByName(ctx context.Context, name string) (AuthProfile, error)
	GetHourlyJobStatsSince(ctx context.Context, createdAt time.Time) ([]GetHourlyJobStatsSinceRow, error)
	GetJobHistoryById(ctx context.Context, id int64) (JobHistory, error)
	GetJobStatsSince(ctx context.Context, createdAt time.Time) (GetJobStatsSinceRow, error)
	GetLatestRenovateRunByPoolId(ctx context.Context, poolID int64) (RenovateRun, error)
	GetOpenJobRow(ctx context.Context, arg GetOpenJobRowParams) (int64, error)
	GetOpenWebhookJobByID(ctx context.Context, jobID sql.NullInt64) (GetOpenWebhookJobByIDRow, error)
	GetPoolByTargetUrl(ctx context.Context, targetUrl string) (RunnerPool, error)
	GetRenovateConfigByPoolId(ctx context.Context, poolID int64) (RenovateConfig, error)
	GetRenovateRun(ctx context.Context, id int64) (RenovateRun, error)
	GetRenovateRunByContainerID(ctx context.Context, containerID sql.NullString) (RenovateRun, error)
	GetRunnerPoolById(ctx context.Context, id int64) (RunnerPool, error)
	GetRunnerPoolByName(ctx context.Context, name string) (RunnerPool, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	// Webhook 'in_progress' with no pre-existing row at all (docs/21 section 5.5 merge rule 4).
	InsertWebhookRunningJob(ctx context.Context, arg InsertWebhookRunningJobParams) error
	ListAdminUsers(ctx context.Context) ([]AdminUser, error)
	ListAllPoolTargets(ctx context.Context) ([]PoolTarget, error)
	ListAppSettings(ctx context.Context) ([]AppSetting, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByUserId(ctx context.Context, arg ListAuditLogsByUserIdParams) ([]AuditLog, error)
	ListAuthProfiles(ctx context.Context) ([]AuthProfile, error)
	ListEnabledRenovateConfigs(ctx context.Context) ([]RenovateConfig, error)
	ListJobHistory(ctx context.Context, arg ListJobHistoryParams) ([]JobHistory, error)
	ListJobHistoryByPoolId(ctx context.Context, arg ListJobHistoryByPoolIdParams) ([]JobHistory, error)
	ListPoolTargetsByPoolId(ctx context.Context, poolID int64) ([]PoolTarget, error)
	ListPoolsByTargetUrl(ctx context.Context, targetUrl string) ([]RunnerPool, error)
	ListRenovateConfigs(ctx context.Context) ([]RenovateConfig, error)
	ListRenovateRunsByPoolId(ctx context.Context, arg ListRenovateRunsByPoolIdParams) ([]RenovateRun, error)
	ListRunnerPools(ctx context.Context) ([]RunnerPool, error)
	ListSessionsByUserId(ctx context.Context, userID int64) ([]Session, error)
	OpenJobLifecycleRow(ctx context.Context, arg OpenJobLifecycleRowParams) (JobHistory, error)
	// Webhook 'in_progress' with a queued stub but no transition row: promote the
	// stub in place (docs/21 section 5.5 merge rule 2).
	PromoteWebhookStubToRunning(ctx context.Context, arg PromoteWebhookStubToRunningParams) (int64, error)
	PruneJobHistoryOlderThan(ctx context.Context, arg PruneJobHistoryOlderThanParams) ([]PruneJobHistoryOlderThanRow, error)
	SearchJobHistory(ctx context.Context, arg SearchJobHistoryParams) ([]JobHistory, error)
	SetAppSetting(ctx context.Context, arg SetAppSettingParams) (AppSetting, error)
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) (AdminUser, error)
	UpdateAuthProfile(ctx context.Context, arg UpdateAuthProfileParams) (AuthProfile, error)
	UpdateJobHistoryStatus(ctx context.Context, arg UpdateJobHistoryStatusParams) (JobHistory, error)
	UpdateRenovateConfig(ctx context.Context, arg UpdateRenovateConfigParams) (RenovateConfig, error)
	UpdateRenovateRunContainerID(ctx context.Context, arg UpdateRenovateRunContainerIDParams) error
	UpdateRunnerPool(ctx context.Context, arg UpdateRunnerPoolParams) (RunnerPool, error)
	// Webhook 'queued' upsert keyed by the external job id (docs/21 section 5.5).
	// Conflicts only fill in missing metadata: status, runner assignment, and the
	// original queued_at are never rewritten by a (re)delivery.
	UpsertWebhookQueuedJob(ctx context.Context, arg UpsertWebhookQueuedJobParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
