// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runner_pools.sql

package db

import (
	"context"
	"database/sql"
)

const countRunnerPools = `-- name: CountRunnerPools :one
SELECT COUNT(*) FROM runner_pools
`

func (q *Queries) CountRunnerPools(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunnerPools)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRunnerPool = `-- name: CreateRunnerPool :one
INSERT INTO runner_pools (
    name,
    provider,
    repository_url,
    scope,
    auth_profile_id,
    min_idle_runners,
    max_concurrency,
    labels,
    runner_image,
    allow_docker,
    max_runner_lifetime_seconds,
    cpu_limit,
    memory_limit,
    poll_fallback,
    poll_interval_seconds
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, name, provider, repository_url, scope, auth_profile_id, min_idle_runners, max_concurrency, labels, runner_image, allow_docker, max_runner_lifetime_seconds, cpu_limit, memory_limit, created_at, updated_at, poll_fallback, poll_interval_seconds
`

type CreateRunnerPoolParams struct {
	Name                     string         `json:"name"`
	Provider                 string         `json:"provider"`
	RepositoryUrl            string         `json:"repository_url"`
	Scope                    string         `json:"scope"`
	AuthProfileID            int64          `json:"auth_profile_id"`
	MinIdleRunners           int64          `json:"min_idle_runners"`
	MaxConcurrency           int64          `json:"max_concurrency"`
	Labels                   string         `json:"labels"`
	RunnerImage              string         `json:"runner_image"`
	AllowDocker              bool           `json:"allow_docker"`
	MaxRunnerLifetimeSeconds int64          `json:"max_runner_lifetime_seconds"`
	CpuLimit                 sql.NullString `json:"cpu_limit"`
	MemoryLimit              sql.NullString `json:"memory_limit"`
	PollFallback             bool           `json:"poll_fallback"`
	PollIntervalSeconds      int64          `json:"poll_interval_seconds"`
}

func (q *Queries) CreateRunnerPool(ctx context.Context, arg CreateRunnerPoolParams) (RunnerPool, error) {
	row := q.db.QueryRowContext(ctx, createRunnerPool,
		arg.Name,
		arg.Provider,
		arg.RepositoryUrl,
		arg.Scope,
		arg.AuthProfileID,
		arg.MinIdleRunners,
		arg.MaxConcurrency,
		arg.Labels,
		arg.RunnerImage,
		arg.AllowDocker,
		arg.MaxRunnerLifetimeSeconds,
		arg.CpuLimit,
		arg.MemoryLimit,
		arg.PollFallback,
		arg.PollIntervalSeconds,
	)
	var i RunnerPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.RepositoryUrl,
		&i.Scope,
		&i.AuthProfileID,
		&i.MinIdleRunners,
		&i.MaxConcurrency,
		&i.Labels,
		&i.RunnerImage,
		&i.AllowDocker,
		&i.MaxRunnerLifetimeSeconds,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PollFallback,
		&i.PollIntervalSeconds,
	)
	return i, err
}

const deleteRunnerPool = `-- name: DeleteRunnerPool :exec
DELETE FROM runner_pools
WHERE id = ?
`

func (q *Queries) DeleteRunnerPool(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunnerPool, id)
	return err
}

const getRunnerPoolById = `-- name: GetRunnerPoolById :one
SELECT id, name, provider, repository_url, scope, auth_profile_id, min_idle_runners, max_concurrency, labels, runner_image, allow_docker, max_runner_lifetime_seconds, cpu_limit, memory_limit, created_at, updated_at, poll_fallback, poll_interval_seconds FROM runner_pools
WHERE id = ? LIMIT 1
`

func (q *Queries) GetRunnerPoolById(ctx context.Context, id int64) (RunnerPool, error) {
	row := q.db.QueryRowContext(ctx, getRunnerPoolById, id)
	var i RunnerPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.RepositoryUrl,
		&i.Scope,
		&i.AuthProfileID,
		&i.MinIdleRunners,
		&i.MaxConcurrency,
		&i.Labels,
		&i.RunnerImage,
		&i.AllowDocker,
		&i.MaxRunnerLifetimeSeconds,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PollFallback,
		&i.PollIntervalSeconds,
	)
	return i, err
}

const getRunnerPoolByName = `-- name: GetRunnerPoolByName :one
SELECT id, name, provider, repository_url, scope, auth_profile_id, min_idle_runners, max_concurrency, labels, runner_image, allow_docker, max_runner_lifetime_seconds, cpu_limit, memory_limit, created_at, updated_at, poll_fallback, poll_interval_seconds FROM runner_pools
WHERE name = ? LIMIT 1
`

func (q *Queries) GetRunnerPoolByName(ctx context.Context, name string) (RunnerPool, error) {
	row := q.db.QueryRowContext(ctx, getRunnerPoolByName, name)
	var i RunnerPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.RepositoryUrl,
		&i.Scope,
		&i.AuthProfileID,
		&i.MinIdleRunners,
		&i.MaxConcurrency,
		&i.Labels,
		&i.RunnerImage,
		&i.AllowDocker,
		&i.MaxRunnerLifetimeSeconds,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PollFallback,
		&i.PollIntervalSeconds,
	)
	return i, err
}

const listRunnerPools = `-- name: ListRunnerPools :many
SELECT id, name, provider, repository_url, scope, auth_profile_id, min_idle_runners, max_concurrency, labels, runner_image, allow_docker, max_runner_lifetime_seconds, cpu_limit, memory_limit, created_at, updated_at, poll_fallback, poll_interval_seconds FROM runner_pools
ORDER BY name ASC
`

func (q *Queries) ListRunnerPools(ctx context.Context) ([]RunnerPool, error) {
	rows, err := q.db.QueryContext(ctx, listRunnerPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunnerPool{}
	for rows.Next() {
		var i RunnerPool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.RepositoryUrl,
			&i.Scope,
			&i.AuthProfileID,
			&i.MinIdleRunners,
			&i.MaxConcurrency,
			&i.Labels,
			&i.RunnerImage,
			&i.AllowDocker,
			&i.MaxRunnerLifetimeSeconds,
			&i.CpuLimit,
			&i.MemoryLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PollFallback,
			&i.PollIntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunnerPool = `-- name: UpdateRunnerPool :one
UPDATE runner_pools
SET name = ?,
    provider = ?,
    repository_url = ?,
    scope = ?,
    auth_profile_id = ?,
    min_idle_runners = ?,
    max_concurrency = ?,
    labels = ?,
    runner_image = ?,
    allow_docker = ?,
    max_runner_lifetime_seconds = ?,
    cpu_limit = ?,
    memory_limit = ?,
    poll_fallback = ?,
    poll_interval_seconds = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, provider, repository_url, scope, auth_profile_id, min_idle_runners, max_concurrency, labels, runner_image, allow_docker, max_runner_lifetime_seconds, cpu_limit, memory_limit, created_at, updated_at, poll_fallback, poll_interval_seconds
`

type UpdateRunnerPoolParams struct {
	Name                     string         `json:"name"`
	Provider                 string         `json:"provider"`
	RepositoryUrl            string         `json:"repository_url"`
	Scope                    string         `json:"scope"`
	AuthProfileID            int64          `json:"auth_profile_id"`
	MinIdleRunners           int64          `json:"min_idle_runners"`
	MaxConcurrency           int64          `json:"max_concurrency"`
	Labels                   string         `json:"labels"`
	RunnerImage              string         `json:"runner_image"`
	AllowDocker              bool           `json:"allow_docker"`
	MaxRunnerLifetimeSeconds int64          `json:"max_runner_lifetime_seconds"`
	CpuLimit                 sql.NullString `json:"cpu_limit"`
	MemoryLimit              sql.NullString `json:"memory_limit"`
	PollFallback             bool           `json:"poll_fallback"`
	PollIntervalSeconds      int64          `json:"poll_interval_seconds"`
	ID                       int64          `json:"id"`
}

func (q *Queries) UpdateRunnerPool(ctx context.Context, arg UpdateRunnerPoolParams) (RunnerPool, error) {
	row := q.db.QueryRowContext(ctx, updateRunnerPool,
		arg.Name,
		arg.Provider,
		arg.RepositoryUrl,
		arg.Scope,
		arg.AuthProfileID,
		arg.MinIdleRunners,
		arg.MaxConcurrency,
		arg.Labels,
		arg.RunnerImage,
		arg.AllowDocker,
		arg.MaxRunnerLifetimeSeconds,
		arg.CpuLimit,
		arg.MemoryLimit,
		arg.PollFallback,
		arg.PollIntervalSeconds,
		arg.ID,
	)
	var i RunnerPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.RepositoryUrl,
		&i.Scope,
		&i.AuthProfileID,
		&i.MinIdleRunners,
		&i.MaxConcurrency,
		&i.Labels,
		&i.RunnerImage,
		&i.AllowDocker,
		&i.MaxRunnerLifetimeSeconds,
		&i.CpuLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PollFallback,
		&i.PollIntervalSeconds,
	)
	return i, err
}
