// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    token_hash,
    expires_at,
    absolute_expires_at,
    user_agent
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, user_id, token_hash, expires_at, created_at, user_agent, last_seen_at, absolute_expires_at
`

type CreateSessionParams struct {
	UserID            int64     `json:"user_id"`
	TokenHash         string    `json:"token_hash"`
	ExpiresAt         time.Time `json:"expires_at"`
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
	UserAgent         string    `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions
WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteSessionsByUserId = `-- name: DeleteSessionsByUserId :exec
DELETE FROM sessions
WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUserId(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserId, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, expires_at, created_at, user_agent, last_seen_at, absolute_expires_at FROM sessions
WHERE token_hash = ? LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const listSessionsByUserId = `-- name: ListSessionsByUserId :many
SELECT id, user_id, token_hash, expires_at, created_at, user_agent, last_seen_at, absolute_expires_at FROM sessions
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByUserId(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UserAgent,
			&i.LastSeenAt,
			&i.AbsoluteExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at < ?1 OR absolute_expires_at < ?1
`

// Hourly maintenance (docs/32 section 5.2): delete sessions past either
// clock - the sliding idle deadline or the fixed absolute cap.
func (q *Queries) PurgeExpiredSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET expires_at = ?,
    last_seen_at = CURRENT_TIMESTAMP
WHERE token_hash = ?
`

type TouchSessionParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	TokenHash string    `json:"token_hash"`
}

// Sliding renewal (docs/32 section 3.3): extend the idle deadline and record
// the activity instant. Callers clamp expires_at at absolute_expires_at before
// writing: the cap is never extended.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.ExpiresAt, arg.TokenHash)
	return err
}
