// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_credentials.sql

package db

import (
	"context"
	"time"
)

const countWebauthnCredentialsByUserId = `-- name: CountWebauthnCredentialsByUserId :one
SELECT count(*) FROM webauthn_credentials WHERE user_id = ?
`

func (q *Queries) CountWebauthnCredentialsByUserId(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebauthnCredentialsByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebauthnCredential = `-- name: CreateWebauthnCredential :one

INSERT INTO webauthn_credentials (
    user_id, name, credential_id, public_key, aaguid, attestation_type,
    transports, sign_count, backup_eligible, backup_state, clone_warning
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?
)
RETURNING id, user_id, name, credential_id, public_key, aaguid, attestation_type, transports, sign_count, backup_eligible, backup_state, clone_warning, created_at, last_used_at
`

type CreateWebauthnCredentialParams struct {
	UserID          int64  `json:"user_id"`
	Name            string `json:"name"`
	CredentialID    []byte `json:"credential_id"`
	PublicKey       []byte `json:"public_key"`
	Aaguid          string `json:"aaguid"`
	AttestationType string `json:"attestation_type"`
	Transports      string `json:"transports"`
	SignCount       int64  `json:"sign_count"`
	BackupEligible  int64  `json:"backup_eligible"`
	BackupState     int64  `json:"backup_state"`
	CloneWarning    int64  `json:"clone_warning"`
}

// WebAuthn credential storage (RUN-247, docs/34 sections 3.6 and 6). Rows
// are public material only: COSE public keys, credential IDs, counters and
// flags. The credential_id UNIQUE column is the passwordless-login identity
// lookup (docs/34 section 3.2); ownership-scoped statements carry user_id so
// a caller can only ever touch their own rows (docs/34 section 3.9).
func (q *Queries) CreateWebauthnCredential(ctx context.Context, arg CreateWebauthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, createWebauthnCredential,
		arg.UserID,
		arg.Name,
		arg.CredentialID,
		arg.PublicKey,
		arg.Aaguid,
		arg.AttestationType,
		arg.Transports,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
		arg.CloneWarning,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.AttestationType,
		&i.Transports,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.CloneWarning,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteWebauthnCredentialByIdAndUserId = `-- name: DeleteWebauthnCredentialByIdAndUserId :execrows
DELETE FROM webauthn_credentials WHERE id = ? AND user_id = ?
`

type DeleteWebauthnCredentialByIdAndUserIdParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteWebauthnCredentialByIdAndUserId(ctx context.Context, arg DeleteWebauthnCredentialByIdAndUserIdParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWebauthnCredentialByIdAndUserId, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWebauthnCredentialById = `-- name: GetWebauthnCredentialById :one
SELECT id, user_id, name, credential_id, public_key, aaguid, attestation_type, transports, sign_count, backup_eligible, backup_state, clone_warning, created_at, last_used_at FROM webauthn_credentials WHERE credential_id = ?
`

// The passwordless-login identity lookup: raw credential ID to row (docs/34
// section 3.2).
func (q *Queries) GetWebauthnCredentialById(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, getWebauthnCredentialById, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.AttestationType,
		&i.Transports,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.CloneWarning,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getWebauthnCredentialByIdAndUserId = `-- name: GetWebauthnCredentialByIdAndUserId :one
SELECT id, user_id, name, credential_id, public_key, aaguid, attestation_type, transports, sign_count, backup_eligible, backup_state, clone_warning, created_at, last_used_at FROM webauthn_credentials WHERE id = ? AND user_id = ?
`

type GetWebauthnCredentialByIdAndUserIdParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Ownership-scoped single-row fetch for Rename/Delete pre-checks.
func (q *Queries) GetWebauthnCredentialByIdAndUserId(ctx context.Context, arg GetWebauthnCredentialByIdAndUserIdParams) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, getWebauthnCredentialByIdAndUserId, arg.ID, arg.UserID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.AttestationType,
		&i.Transports,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.CloneWarning,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listWebauthnCredentialsByUserId = `-- name: ListWebauthnCredentialsByUserId :many
SELECT id, user_id, name, credential_id, public_key, aaguid, attestation_type, transports, sign_count, backup_eligible, backup_state, clone_warning, created_at, last_used_at FROM webauthn_credentials WHERE user_id = ? ORDER BY created_at, id
`

func (q *Queries) ListWebauthnCredentialsByUserId(ctx context.Context, userID int64) ([]WebauthnCredential, error) {
	rows, err := q.db.QueryContext(ctx, listWebauthnCredentialsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CredentialID,
			&i.PublicKey,
			&i.Aaguid,
			&i.AttestationType,
			&i.Transports,
			&i.SignCount,
			&i.BackupEligible,
			&i.BackupState,
			&i.CloneWarning,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameWebauthnCredential = `-- name: RenameWebauthnCredential :execrows
UPDATE webauthn_credentials SET name = ? WHERE id = ? AND user_id = ?
`

type RenameWebauthnCredentialParams struct {
	Name   string `json:"name"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) RenameWebauthnCredential(ctx context.Context, arg RenameWebauthnCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameWebauthnCredential, arg.Name, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setWebauthnCredentialCloneWarning = `-- name: SetWebauthnCredentialCloneWarning :exec
UPDATE webauthn_credentials SET clone_warning = 1 WHERE credential_id = ?
`

// Fail-closed flag on a non-increasing sign counter (docs/34 section 3.8):
// a flagged credential refuses all further assertions until removed.
func (q *Queries) SetWebauthnCredentialCloneWarning(ctx context.Context, credentialID []byte) error {
	_, err := q.db.ExecContext(ctx, setWebauthnCredentialCloneWarning, credentialID)
	return err
}

const updateWebauthnCredentialAssertionState = `-- name: UpdateWebauthnCredentialAssertionState :exec
UPDATE webauthn_credentials
SET sign_count = ?, backup_eligible = ?, backup_state = ?, last_used_at = ?
WHERE credential_id = ?
`

type UpdateWebauthnCredentialAssertionStateParams struct {
	SignCount      int64     `json:"sign_count"`
	BackupEligible int64     `json:"backup_eligible"`
	BackupState    int64     `json:"backup_state"`
	LastUsedAt     time.Time `json:"last_used_at"`
	CredentialID   []byte    `json:"credential_id"`
}

// Called after every successful assertion (docs/34 section 3.8): the
// library's counter policy result plus the response's backup flags and the
// last-use stamp.
func (q *Queries) UpdateWebauthnCredentialAssertionState(ctx context.Context, arg UpdateWebauthnCredentialAssertionStateParams) error {
	_, err := q.db.ExecContext(ctx, updateWebauthnCredentialAssertionState,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
		arg.LastUsedAt,
		arg.CredentialID,
	)
	return err
}
